import {triggerSeoCheck} from '@/lib/seo-trigger';
import {adminSession,sameOrigin} from '@/lib/admin-auth';
import {validArtist} from '@/lib/site-config';
import {channelDb} from '@/lib/channel-db';
export const dynamic='force-dynamic';
export async function GET(request:Request){if(!adminSession(request))return new Response(null,{status:401});const artist=new URL(request.url).searchParams.get('artist')??'';if(!validArtist(artist))return new Response(null,{status:404});try{const row=await channelDb().prepare('SELECT biography,sources,revision,updated FROM artist_content WHERE artist=?').bind(artist).first();return Response.json(row??{biography:'',sources:'',revision:0},{headers:{'Cache-Control':'no-store'}})}catch{return Response.json({error:'İçerik yüklenemedi.'},{status:503})}}
async function savePost(request:Request){if(!adminSession(request)||!sameOrigin(request))return new Response(null,{status:403});const raw=await request.text();if(raw.length>30000)return new Response(null,{status:413});let d;try{d=JSON.parse(raw)}catch{return new Response(null,{status:400})}if(!d||!validArtist(d.artist)||typeof d.biography!=='string'||typeof d.sources!=='string'||d.biography.length>20000||d.sources.length>5000||!Number.isInteger(d.revision))return Response.json({error:'Alanlar geçersiz veya çok uzun.'},{status:400});const urls=d.sources.split('\n').map((x:string)=>x.trim()).filter(Boolean);if(urls.some((x:string)=>{try{return new URL(x).protocol!=='https:'}catch{return true}}))return Response.json({error:'Kaynaklar her satırda bir HTTPS adresi olmalı.'},{status:400});try{const result=await channelDb().prepare('INSERT INTO artist_content (artist,biography,sources,updated,revision) SELECT ?,?,?,?,1 WHERE ?=0 ON CONFLICT(artist) DO NOTHING RETURNING revision').bind(d.artist,d.biography,d.sources,Date.now(),d.revision).first();if(d.revision===0&&!result)return Response.json({error:'İçerik başka bir oturumda değişti. Yeniden yükle.'},{status:409});if(d.revision!==0){const updated=await channelDb().prepare('UPDATE artist_content SET biography=?,sources=?,updated=?,revision=revision+1 WHERE artist=? AND revision=? RETURNING revision').bind(d.biography,d.sources,Date.now(),d.artist,d.revision).first();if(!updated)return Response.json({error:'İçerik başka bir oturumda değişti. Yeniden yükle.'},{status:409});return Response.json(updated)}return Response.json(result)}catch(e){console.error('content save failed',e);return Response.json({error:'Kaydedilemedi. Yazdıkların korunuyor.'},{status:503})}}

export async function POST(request:Request){const response=await savePost(request);if(response.ok)triggerSeoCheck();return response}
