'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {artistIds,siteConfig} from '@/lib/site-config';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
export default function Admin(){const [authorized,setAuthorized]=useState(false),[checking,setChecking]=useState(true),[password,setPassword]=useState(''),[artist,setArtist]=useState<string>('semicenk'),[bio,setBio]=useState(''),[sources,setSources]=useState(''),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[dirty,setDirty]=useState(false);
useEffect(()=>{fetch('/api/admin/session',{cache:'no-store'}).then(r=>r.json()).then(d=>setAuthorized(d.authenticated)).catch(()=>setError('Giriş durumu kontrol edilemedi.')).finally(()=>setChecking(false))},[]);
useEffect(()=>{if(!authorized)return;const controller=new AbortController();setBusy(true);setError('');fetch('/api/admin/content?artist='+artist,{signal:controller.signal,cache:'no-store'}).then(async r=>{if(r.status===401){setAuthorized(false);throw new Error('Oturum sona erdi.')}const d=await r.json();if(!r.ok)throw new Error(d.error);setBio(d.biography);setSources(d.sources);setRevision(d.revision);setDirty(false)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[artist,authorized]);
async function login(){setBusy(true);setError('');try{const r=await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const d=await r.json();if(!r.ok)throw new Error(d.error);setPassword('');setAuthorized(true)}catch(e){setError(e instanceof Error?e.message:'Giriş yapılamadı.')}finally{setBusy(false)}}
async function save(){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/content',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({artist,biography:bio,sources,revision})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Kayıt yapılamadı.');setRevision(d.revision);setDirty(false);setNotice('Kaydedildi. Biyografi sayfası güncellendi.')}catch(e){setError(e instanceof Error?e.message:'Kayıt yapılamadı.')}finally{setBusy(false)}}
return <main className="admin-page"><header><Link className="brand" href="/">{siteConfig.mark}<span>✳</span></Link><span>İçerik yönetimi</span>{authorized&&<button onClick={async()=>{await fetch('/api/admin/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});setAuthorized(false)}}>Çıkış yap</button>}</header>{checking?<p>Giriş kontrol ediliyor…</p>:!authorized?<section className="admin-login"><h1>Yönetici girişi</h1><p>Sanatçı içeriklerini ve kanalları buradan yönet.</p><form onSubmit={e=>{e.preventDefault();void login()}}><label className="tool-label">Yönetici parolası<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="tool-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Kontrol ediliyor…':'Giriş yap'}</button></form></section>:<section className="admin-editor"><h1>Sanatçı içerikleri</h1><Link className="primary" href="/admin/icerikler">Haber, konser ve albüm yönetimi →</Link><p><Link href="/admin/seo">SEO merkezi →</Link></p><p>Biyografi metnini ve doğruladığın kaynakları ekle.</p><Tabs value={artist} onValueChange={v=>{if(!dirty){setArtist(v);setNotice('')}else setError('Sanatçı değiştirmeden önce değişikliklerini kaydet.')}}><TabsList className="admin-artists">{artistIds.map(a=><TabsTrigger disabled={busy} key={a} value={a}>{a}</TabsTrigger>)}</TabsList></Tabs><form onSubmit={e=>{e.preventDefault();void save()}}><label className="tool-label">Biyografi<textarea disabled={busy} value={bio} maxLength={20000} onChange={e=>{setBio(e.target.value);setDirty(true)}} placeholder="Doğrulanmış sanatçı biyografisi…"/></label><label className="tool-label">Kaynaklar · Her satırda bir HTTPS bağlantısı<textarea disabled={busy} value={sources} maxLength={5000} onChange={e=>{setSources(e.target.value);setDirty(true)}} placeholder="https://…"/></label>{error&&<p className="tool-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}<div className="actions"><button className="primary" disabled={busy||!dirty}>{busy?'İşleniyor…':'Kaydet ve güncelle'}</button><Link className="secondary" target="_blank" href={'/'+artist+'/biyografi'}>Sayfayı gör</Link><Link className="secondary" href={'/'+artist+'#kanal'}>Kanal moderasyonu</Link></div></form></section>}</main>}
