import ts from 'typescript';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import assert from 'node:assert/strict';
const sql=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sql.exec(fs.readFileSync('drizzle/'+file,'utf8'));
globalThis.channelTestDb={async batch(statements){sql.exec('BEGIN');try{const results=[];for(const q of statements)results.push(await q.run());sql.exec('COMMIT');return results}catch(e){sql.exec('ROLLBACK');throw e}},prepare(query){let args=[];return {bind(...a){args=a;return this},async first(){return sql.prepare(query).get(...args)??null},async all(){return {results:sql.prepare(query).all(...args)}},async run(){return sql.prepare(query).run(...args)}}}};
globalThis.testModerator=request=>request.headers.get('x-test-admin')==='test-owner'?'verified-owner-id':null;
let source=fs.readFileSync('app/api/channels/[artist]/route.ts','utf8').replace("import {channelDb, type Statement} from '@/lib/channel-db';","const channelDb=()=>globalThis.channelTestDb;").replace("import {validArtist} from '@/lib/site-config';","const validArtist=id=>['semicenk','tarkan','mabel-matiz','manifest'].includes(id);");
source=source.replace("import {moderatorIdentity} from '@/lib/moderation-auth';","const moderatorIdentity=globalThis.testModerator;");
const {outputText}=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}});
const {GET,POST}=await import('data:text/javascript;base64,'+Buffer.from(outputText).toString('base64'));
const ctx=artist=>({params:Promise.resolve({artist})});
const post=(artist,data,cookie='',origin='https://test.local')=>POST(new Request('https://test.local/api/channels/'+artist,{method:'POST',headers:{'Content-Type':'application/json','Origin':origin,'Cookie':cookie},body:JSON.stringify(data)}),ctx(artist));
const get=(artist,cookie='')=>GET(new Request('https://test.local/api/channels/'+artist,{headers:{Cookie:cookie}}),ctx(artist));
assert.equal((await get('semicenk')).status,401);
assert.equal((await post('semicenk',{action:'join'},'','https://evil.test')).status,403);
const a=await post('semicenk',{action:'join'});assert.equal(a.status,200);const ca=a.headers.get('set-cookie').split(';')[0];
const b=await post('semicenk',{action:'join'});const cb=b.headers.get('set-cookie').split(';')[0];assert.notEqual(ca,cb);
const id=crypto.randomUUID();assert.equal((await post('semicenk',{action:'message',id,body:'Merhaba ortak kanal'},ca)).status,201);
const read=await (await get('semicenk',cb)).json();assert.equal(read.messages.length,1);assert.equal(read.messages[0].body,'Merhaba ortak kanal');assert.equal(read.messages[0].own,false);assert.equal(read.online,2);
assert.equal((await post('semicenk',{action:'message',id,body:'Merhaba ortak kanal'},ca)).status,200);
assert.equal((await post('semicenk',{action:'message',id:crypto.randomUUID(),body:'Flood'},ca)).status,429);
await post('tarkan',{action:'join'},cb);const other=await(await get('tarkan',cb)).json();assert.equal(other.messages.length,0);
assert.equal((await post('semicenk',{action:'message',id:crypto.randomUUID(),body:'x'.repeat(1001)},cb)).status,400);
assert.equal((await get('olmayan',cb)).status,404);
assert.equal((await(await get('semicenk',ca)).json()).messages[0].own,true);
console.log('PASS: 2 guests, shared messages, persistence across requests, channel isolation, idempotency, rate limit, origin rejection, length validation and missing channel.');

const adminHeaders={'x-test-admin':'test-owner'};
const adminPost=(artist,data)=>POST(new Request('https://test.local/api/channels/'+artist,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://test.local',Cookie:ca,...adminHeaders},body:JSON.stringify(data)}),ctx(artist));
const adminGet=artist=>GET(new Request('https://test.local/api/channels/'+artist,{headers:{Cookie:ca,...adminHeaders}}),ctx(artist));
assert.equal(globalThis.testModerator(new Request('https://test.local',{headers:{'oai-authenticated-user-email':'owner@example.test'}})),null);
assert.equal(globalThis.testModerator(new Request('https://test.local',{headers:{'oai-authenticated-user-id':'other','oai-authenticated-user-email':'other@example.test'}})),null);
assert.equal((await post('semicenk',{action:'rename',name:'Deniz'},cb)).status,200);
let renamed=await(await get('semicenk',cb)).json();assert.match(renamed.guest.name,/^Deniz #[A-F0-9]{6}$/);
assert.equal((await post('semicenk',{action:'rename',name:'Ece'},cb)).status,429);
assert.equal((await post('semicenk',{action:'rename',name:'Admin'},cb)).status,400);
assert.equal((await post('tarkan',{action:'report',messageId:id,reason:'Başka kanaldaki mesaj'},cb)).status,404);
assert.equal((await post('semicenk',{action:'report',messageId:id,reason:'Uygunsuz içerik örneği'},cb)).status,201);
assert.equal((await post('semicenk',{action:'report',messageId:id,reason:'Uygunsuz içerik örneği'},cb)).status,200);
assert.equal((await(await get('semicenk',cb)).json()).moderation,null);
assert.equal((await post('semicenk',{action:'delete',messageId:id,reason:'Yetkisiz deneme'},cb)).status,403);
assert.equal((await post('semicenk',{action:'mute',messageId:id,reason:'Yetkisiz deneme'},cb)).status,403);
let panel=await(await adminGet('semicenk')).json();assert.equal(panel.moderation.reports.length,1);
assert.equal((await adminPost('tarkan',{action:'delete',messageId:id,reason:'Yanlış kanal testi'})).status,404);
assert.equal((await adminPost('semicenk',{action:'mute',messageId:id,reason:'Tekrarlı mesaj testi'})).status,200);
assert.equal((await post('semicenk',{action:'message',id:crypto.randomUUID(),body:'Susturulmuş mesaj'},ca)).status,403);
assert.equal((await post('semicenk',{action:'rename',name:'YeniAd'},ca)).status,200);
assert.equal((await post('semicenk',{action:'message',id:crypto.randomUUID(),body:'Ad değişince kaçış'},ca)).status,403);
panel=await(await adminGet('semicenk')).json();assert.equal(panel.moderation.mutes.length,1);assert.equal(panel.moderation.audit.length,1);
assert.equal((await adminPost('semicenk',{action:'unmute',guestId:panel.moderation.mutes[0].guest_id,reason:'İnceleme tamamlandı'})).status,200);
assert.equal((await adminPost('semicenk',{action:'delete',messageId:id,reason:'Topluluk kuralı ihlali'})).status,200);
const hidden=await(await get('semicenk',cb)).json();assert.equal(hidden.messages[0].deleted,true);assert.notEqual(hidden.messages[0].body,'Merhaba ortak kanal');
panel=await(await adminGet('semicenk')).json();assert.equal(panel.moderation.reports.length,0);assert.equal(panel.moderation.mutes.length,0);assert.equal(panel.moderation.audit.length,3);
assert.equal(sql.prepare('SELECT body FROM channel_messages WHERE id=?').get(id).body,'Merhaba ortak kanal');
console.log('PASS: moderation authorization with test identity adapter, unauthorized rejection, nickname validation/cooldown, report deduplication and privacy, cross-channel isolation, mute surviving rename, unmute, soft deletion and atomic audit log.');
