import {fileURLToPath} from 'node:url';
import {dirname,resolve} from 'node:path';
if(process.env.CONTENT_TEST_ONLY!=='1'||!process.env.PLAYWRIGHT_MODULE)throw Error('QA only: set CONTENT_TEST_ONLY=1 and PLAYWRIGHT_MODULE');
const {chromium,request}=await import(process.env.PLAYWRIGHT_MODULE);
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),base='http://127.0.0.1:3043',dbPath=root+'/.data/comments-qa.sqlite';
assert(dbPath.includes('/.data/comments-qa.sqlite'));
const db=new DatabaseSync(dbPath),target='section:semicenk:biyografi';
db.prepare('DELETE FROM page_comment_likes WHERE comment_id IN (SELECT id FROM page_comments WHERE target=?)').run(target);
db.prepare('DELETE FROM page_comments WHERE target=?').run(target);
const guest=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base,'X-Real-IP':'198.51.100.11'}});
const admin=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}});
assert.equal((await guest.get('/api/admin/comments')).status(),401);
assert.equal((await guest.patch('/api/admin/comments',{data:{}})).status(),401);
let r=await guest.post('/api/engagement',{data:{target,action:'comment',name:'QA Misafir',body:'Onay bekleyen gizli QA yorum'}});
assert.equal(r.status(),201,await r.text());
let d=await (await guest.get('/api/engagement?target='+target)).json();assert.equal(d.commentCount,0);assert.equal(d.comments.length,0);
assert.equal((await (await guest.get('/api/engagement/stats?targets='+target)).json()).stats[target].comments,0);
assert.equal((await guest.post('/api/engagement',{data:{target,action:'comment',name:'QA Misafir',body:'Tekrar'}})).status(),429);
assert.equal((await guest.post('/api/engagement',{headers:{Origin:'https://example.org'},data:{target,action:'comment',name:'QA',body:'CSRF'}})).status(),403);
assert.equal((await guest.post('/api/engagement',{data:{target,action:'comment',name:'',body:'No name'}})).status(),400);
assert.equal((await admin.post('/api/admin/session',{data:{password:'QA-only-comments-2026'}})).status(),200);
d=await (await admin.get('/api/admin/comments')).json();let pending=d.comments.find(c=>c.body==='Onay bekleyen gizli QA yorum');assert(pending);
assert.equal((await admin.patch('/api/admin/comments',{data:{id:pending.id,status:'approved',updated:pending.updated}})).status(),200);
d=await (await guest.get('/api/engagement?target='+target)).json();assert.equal(d.commentCount,1);assert.equal(d.comments[0].username,'QA Misafir');assert.equal(d.liked,false);
assert.equal((await (await guest.get('/api/engagement/stats?targets='+target)).json()).stats[target].comments,1);
const row=db.prepare('SELECT updated FROM page_comments WHERE id=?').get(pending.id);
assert.equal((await admin.patch('/api/admin/comments',{data:{id:pending.id,status:'rejected',updated:row.updated}})).status(),200);
assert.equal((await (await guest.get('/api/engagement?target='+target)).json()).commentCount,0);
const now=Date.now();
for(let i=0;i<61;i++)db.prepare("INSERT INTO page_comments(id,target,guest_name,body,created,updated,status) VALUES(?,?,?,?,?,?,'approved')").run(randomUUID(),target,'Okuyucu '+i,i===0?'<script>window.QA_XSS=true</script>':'Onaylı QA yorum '+i+' — '.repeat(15),now+i,now+i);
const first=await (await guest.get('/api/engagement?target='+target+'&limit=50')).json(),second=await (await guest.get('/api/engagement?target='+target+'&limit=50&offset=50')).json();
assert.equal(first.comments.length,50);assert.equal(second.comments.length,11);assert.equal(new Set([...first.comments,...second.comments].map(c=>c.id)).size,61);
const member=await request.newContext({baseURL:base,extraHTTPHeaders:{Origin:base}});
const username='qa'+Date.now();
assert.equal((await member.post('/api/member/session',{data:{action:'register',username,password:'QA-member-password-2026'}})).status(),201);
assert.equal((await member.post('/api/engagement',{data:{target,action:'comment',body:'Üye yorumu da onay bekler'}})).status(),201);
assert.equal((await (await guest.get('/api/engagement?target='+target)).json()).commentCount,61);
assert.equal((await member.post('/api/engagement',{data:{target,action:'like'}})).status(),200);
assert.equal((await (await member.get('/api/engagement?target='+target)).json()).liked,true);
const browser=await chromium.launch({headless:true,executablePath:'/home/deploy/.cache/ms-playwright/chromium_headless_shell-1194/chrome-linux/headless_shell',args:['--no-sandbox'],env:{...process.env,LD_LIBRARY_PATH:'/home/deploy/fans/qa/browser-libs/extracted/usr/lib/x86_64-linux-gnu'}});
const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/semicenk/biyografi',{waitUntil:'domcontentloaded'});
await page.locator('.comment-preview').first().waitFor();
assert.equal(await page.locator('.comment-preview').count(),5);
assert.equal(await page.locator('.engagement-dock').count(),0);
await page.getByRole('button',{name:'Beğeni kutusunu aç',exact:true}).click();
assert.equal(await page.locator('.engagement-dock').count(),1);
await page.getByRole('button',{name:'Beğeni kutusunu kapat',exact:true}).click();
await page.locator('.comment-section').scrollIntoViewIfNeeded();
await page.screenshot({path:root+'/.data/comments-desktop.png'});
await page.getByRole('button',{name:'Tüm yorumlar',exact:true}).click();
await page.locator('.comment-full').first().waitFor();assert.equal(await page.locator('.comment-full').count(),50);
await page.getByRole('button',{name:'Daha fazla yorum göster'}).click();
await page.waitForFunction(()=>document.querySelectorAll('.comment-full').length===61);
assert.equal(await page.evaluate(()=>window.QA_XSS),undefined);
await page.screenshot({path:root+'/.data/comments-drawer-desktop.png'});
await page.keyboard.press('Escape');
await page.locator('.comments-drawer').waitFor({state:'hidden'});
await page.locator('.guest-comment-form').getByLabel('İsmin',{exact:true}).fill('Misafir tarayıcı');
await page.locator('.guest-comment-form').getByLabel('Yorumun',{exact:true}).fill('Tarayıcı üzerinden onay bekleyen yorum');
await page.getByRole('button',{name:'Yorumu gönder',exact:true}).click();
await page.getByRole('status').filter({hasText:'Onaylandıktan sonra'}).waitFor();
assert.equal(await page.locator('.comment-preview').count(),5);
for(const width of [1440,390]){
 await page.setViewportSize({width,height:1000});
 for(const [path,section] of [['/semicenk/biyografi','biyografi'],['/semicenk/sarkilar/tek-yurek','sarkilar'],['/semicenk/sarkilar','sarkilar'],['/semicenk/konserler/konser-2026-10-09','konserler']]){
  await page.goto(base+path,{waitUntil:'domcontentloaded'});
  const links=await page.locator('.similar-artists-grid a').evaluateAll(a=>a.map(e=>e.getAttribute('href')));
  assert.equal(links.length,4);assert(links.every(h=>h.endsWith('/'+section)&&!h.startsWith('/semicenk/')));
  for(const link of links)assert.equal((await page.request.get(base+link)).status(),200);
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow '+path+' '+width);
  await page.locator('.similar-artists').scrollIntoViewIfNeeded();await page.screenshot({path:root+'/.data/recommend-'+section+'-'+width+'.png'});
 }
}
await page.goto(base+'/semicenk/biyografi',{waitUntil:'domcontentloaded'});
await page.getByRole('button',{name:'Tüm yorumlar',exact:true}).click();await page.locator('.comment-full').first().waitFor();
await page.locator('.comments-drawer').evaluate(el=>Promise.all(el.getAnimations().map(a=>a.finished)));
await page.screenshot({path:root+'/.data/comments-drawer-mobile.png'});
const grip=await page.locator('.drawer-grip').boundingBox();assert(grip);
await page.mouse.move(grip.x+20,grip.y+12);await page.mouse.down();await page.mouse.move(grip.x+20,grip.y+140,{steps:8});await page.mouse.up();
await page.locator('.comments-drawer').waitFor({state:'hidden'});
assert.deepEqual(errors,[]);
await browser.close();await guest.dispose();await admin.dispose();await member.dispose();db.close();
console.log('PASS: guest/member pending; approve/reject; hidden public counts; admin authorization; origin/rate checks; pagination 61; XSS escaped; five inline; collapsed dock; modal/drag/Escape; same-section suggestions; 1440/390 no overflow');
