'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {artistIds} from '@/lib/site-config';
import {entryKinds,entryLabels,todayTR,entryHref,type Entry,type EntryKind} from '@/lib/entries-types';
const fresh=(artist:string,kind:EntryKind):Entry=>({id:'',artist,kind,slug:'',title:'',summary:'',body:'',date:todayTR(),time:'',city:'',venue:'',url:'',source:'',cover:'',tracks:'',status:'draft',revision:0,updated:0});
const slugify=(s:string)=>s.toLocaleLowerCase('tr').replace(/ı/g,'i').replace(/ğ/g,'g').replace(/ş/g,'s').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100).replace(/-$/,'');
export default function EditorialAdmin(){
 const [artist,setArtist]=useState<string>('semicenk'),[kind,setKind]=useState<EntryKind>('haberler'),[entries,setEntries]=useState<Entry[]>([]),[form,setForm]=useState<Entry>(fresh('semicenk','haberler')),[busy,setBusy]=useState(true),[authorized,setAuthorized]=useState(true),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{const c=new AbortController();setBusy(true);setError('');fetch('/api/admin/entries?artist='+artist,{signal:c.signal,cache:'no-store'}).then(async r=>{if(r.status===401){setAuthorized(false);return}const d=await r.json();if(!r.ok)throw new Error(d.error);setAuthorized(true);setEntries(d.entries)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[artist,reload]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 const canLeave=()=>!dirty||window.confirm('Kaydedilmemiş değişiklikler silinsin mi?');
 function selectArtist(a:string){if(!canLeave())return;setArtist(a);setForm(fresh(a,kind));setDirty(false);setNotice('')}
 function selectKind(k:EntryKind){if(!canLeave())return;setKind(k);setForm(fresh(artist,k));setDirty(false);setNotice('')}
 function change<K extends keyof Entry>(key:K,value:Entry[K]){setForm(f=>({...f,[key]:value}));setDirty(true);setNotice('')}
 async function save(){setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/admin/entries',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(r.status===403)setAuthorized(false);if(!r.ok)throw new Error(d.error);setForm(d.entry);setEntries(old=>[d.entry,...old.filter(e=>e.id!==d.entry.id)]);setDirty(false);setNotice(d.entry.status==='published'?'Yayınlandı. Sanatçı sayfası güncellendi.':d.entry.status==='archived'?'Arşivlendi. Ziyaretçilere gösterilmiyor.':'Taslak kaydedildi. Ziyaretçilere gösterilmiyor.')}catch(e){setError(e instanceof Error?e.message:'Kaydedilemedi.')}finally{setBusy(false)}}
 const field=(key:'title'|'slug'|'date'|'time'|'city'|'venue'|'url'|'source'|'cover',label:string,type='text',required=false)=><label className="tool-label" key={key}>{label}<input type={type} required={required} value={form[key]} disabled={busy||(key==='slug'&&!!form.id)} maxLength={key==='title'?160:key==='slug'?100:2000} onChange={e=>change(key,e.target.value)} onBlur={()=>{if(key==='title'&&!form.id&&!form.slug)setForm(f=>({...f,slug:slugify(f.title)}))}}/></label>;
 return <main className="admin-page editorial-admin"><header><Link className="brand" href="/">fans<span>✳</span></Link><Link href="/admin" onClick={e=>{if(!canLeave())e.preventDefault()}}>← Yönetim</Link></header><h1>Haber, konser ve albüm yönetimi</h1><p>Taslağını hazırla, kaynağını ekle ve hazır olduğunda yayınla.</p>{!authorized?<section className="admin-login"><h2>Yönetici girişi gerekli</h2><Link className="primary" href="/admin">Giriş sayfasına git</Link></section>:<>
 <div className="editor-filters"><label>Sanatçı<select disabled={busy} value={artist} onChange={e=>selectArtist(e.target.value)}>{artistIds.map(a=><option key={a}>{a}</option>)}</select></label><label>Bölüm<select disabled={busy} value={kind} onChange={e=>selectKind(e.target.value as EntryKind)}>{entryKinds.map(k=><option key={k} value={k}>{entryLabels[k]}</option>)}</select></label></div>
 <div className="editorial-layout"><aside className="entry-manager"><button className="primary" disabled={busy} onClick={()=>{if(canLeave()){setForm(fresh(artist,kind));setDirty(false);setNotice('');setError('')}}}>+ Yeni içerik</button><button className="secondary" disabled={busy} onClick={()=>{if(canLeave()){setDirty(false);setForm(fresh(artist,kind));setReload(n=>n+1)}}}>Listeyi yenile</button>{entries.filter(e=>e.kind===kind).map(e=><button key={e.id} disabled={busy} className={'entry-select '+(form.id===e.id?'selected':'')} onClick={()=>{if(canLeave()){setForm(e);setDirty(false);setNotice('');setError('')}}}><strong>{e.title}</strong><span>{e.status==='published'?'Yayında':e.status==='draft'?'Taslak':'Arşiv'} · {e.date}</span></button>)}{!busy&&!entries.some(e=>e.kind===kind)&&<p>Bu bölümde henüz kayıt yok.</p>}</aside>
 <form className="admin-editor entry-form" onSubmit={e=>{e.preventDefault();void save()}}><h2>{form.id?'İçeriği düzenle':'Yeni '+entryLabels[kind].toLocaleLowerCase('tr')+' içeriği'}</h2>{field('title','Başlık','text',true)}{field('slug','Sayfa adresi · İlk kayıttan sonra sabit kalır','text',true)}<p className="entry-address">/{artist}/{kind}/{form.slug||'sayfa-adresi'}</p>{field('date',kind==='konserler'?'Konser tarihi':kind==='albumler'?'Çıkış tarihi':'Haber tarihi','date',true)}{kind==='konserler'&&<div className="concert-inputs">{field('time','Saat · Türkiye saati','time')}{field('city','Şehir')}{field('venue','Mekân')}</div>}
 <label className="tool-label">Kısa açıklama<textarea maxLength={400} disabled={busy} value={form.summary} onChange={e=>change('summary',e.target.value)}/></label><label className="tool-label">{kind==='haberler'?'Haber metni':'Açıklama'}<textarea maxLength={20000} disabled={busy} value={form.body} onChange={e=>change('body',e.target.value)}/></label>
 {kind==='albumler'&&<label className="tool-label">Şarkı listesi · Her satırda bir şarkı<textarea maxLength={8000} disabled={busy} value={form.tracks} onChange={e=>change('tracks',e.target.value)}/></label>}{field('url',kind==='konserler'?'Resmî bilet / etkinlik bağlantısı':kind==='albumler'?'Dinleme bağlantısı':'İlgili bağlantı','url')}{field('source','Kaynak bağlantısı · Yayın için gerekli','url')}{field('cover','Görsel adresi · Kullanım izni bulunan HTTPS görseli','url')}
 <label className="tool-label">Yayın durumu<select disabled={busy} value={form.status} onChange={e=>change('status',e.target.value as Entry['status'])}><option value="draft">Taslak</option><option value="published">Yayında</option><option value="archived">Arşiv · Ziyaretçilere kapalı</option></select></label>{error&&<p className="tool-error" role="alert">{error}</p>}{notice&&<p className="admin-notice" role="status">{notice}</p>}<div className="actions"><button className="primary" disabled={busy||(!dirty&&!!form.id)}>{busy?'İşleniyor…':'Kaydet'}</button>{form.id&&form.status==='published'&&!dirty&&<Link target="_blank" className="secondary" href={entryHref(form)}>Yayınlanan sayfayı gör</Link>}</div></form></div></>}{!authorized&&error&&<p className="tool-error">{error}</p>}</main>;
}
