import {randomUUID} from 'node:crypto';
import {channelDb} from '@/lib/channel-db';
import {memberSession} from '@/lib/member-auth';
import {sameOrigin,adminSession} from '@/lib/admin-auth';
import {posts,validImage} from '@/lib/fan-social';
export const runtime='nodejs';export const dynamic='force-dynamic';
const json=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){const url=new URL(req.url),username=url.searchParams.get('username'),id=url.searchParams.get('id');const viewer=(await memberSession(req))?.id??null,db=channelDb();if(id){const p=await posts('p.id=?',[id],viewer,1);return p.length?json({post:p[0]}):json({error:'Gönderi bulunamadı.'},404)}if(username){const member=await db.prepare('SELECT id FROM members WHERE username=?').bind(username).first<{id:string}>();return member?json({posts:await posts('p.member_id=?',[member.id],viewer)}):json({error:'Fan bulunamadı.'},404)}return json({posts:await posts('1=1',[],viewer)})}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'İstek doğrulanamadı.'},403);const member=await memberSession(req);if(!member)return json({error:'Paylaşmak için üye olmalısın.'},401);const raw=await req.text();if(raw.length>200000)return json({error:'Görsel çok büyük.'},413);let d:Record<string,unknown>;try{d=JSON.parse(raw)}catch{return json({error:'Geçersiz istek.'},400)}const body=typeof d.body==='string'?d.body.normalize('NFC').trim():'';const image=validImage(d.image),mediaUrl=typeof d.mediaUrl==='string'?d.mediaUrl:'',theme=['dark','lime','violet'].includes(String(d.theme))?String(d.theme):'dark';if((!body&&!image&&!mediaUrl)||body.length>1200||d.image&&!image)return json({error:'Metin 1–1200 karakter olmalı; fotoğraf JPEG ve küçük boyutlu olmalı.'},400);
 const mediaKind=mediaUrl.endsWith('.jpg')?'photo':/\.(mp4|webm)$/.test(mediaUrl)?'video':image?'photo':'text';if(mediaUrl&&!/^\/api\/social\/media\/[a-f0-9-]{36}\.(jpg|mp4|webm)$/.test(mediaUrl))return json({error:'Geçersiz medya.'},400);const db=channelDb(),now=Date.now(),last=await db.prepare('SELECT created FROM fan_posts WHERE member_id=? ORDER BY created DESC LIMIT 1').bind(member.id).first<{created:number}>();if(last&&now-last.created<30000)return json({error:'Yeni paylaşım için 30 saniye bekle.'},429);
 const id=randomUUID();await db.prepare('INSERT INTO fan_posts(id,member_id,body,image,theme,media_url,media_kind,created) VALUES(?,?,?,?,?,?,?,?)').bind(id,member.id,body,image,theme,mediaUrl,mediaKind,now).run();return json({id},201)}
export async function DELETE(req:Request){if(!sameOrigin(req))return json({error:'İstek doğrulanamadı.'},403);const m=await memberSession(req),admin=adminSession(req);if(!m&&!admin)return json({error:'Üye olmalısın.'},401);let d:Record<string,unknown>;try{d=await req.json()}catch{return json({error:'Geçersiz istek.'},400)}const id=typeof d.id==='string'?d.id:'';if(!/^[a-f0-9-]{36}$/.test(id))return json({error:'Geçersiz gönderi.'},400);const result=await channelDb().prepare(admin?'UPDATE fan_posts SET deleted=1 WHERE id=?':'UPDATE fan_posts SET deleted=1 WHERE id=? AND member_id=?').bind(...(admin?[id]:[id,m!.id])).run();return result.changes?json({ok:true}):json({error:'Gönderi bulunamadı.'},404)}
