import {randomUUID} from 'node:crypto';
import {channelDb} from '@/lib/channel-db';
import {memberSession} from '@/lib/member-auth';
import {sameOrigin} from '@/lib/admin-auth';
export const runtime='nodejs';export const dynamic='force-dynamic';
const media=/^\/api\/social\/media\/[a-f0-9-]{36}\.(jpg|mp4|webm)$/;
export async function GET(req:Request){const username=new URL(req.url).searchParams.get('username')??'',db=channelDb(),now=Date.now();const rows=await db.prepare(`SELECT s.id,s.body,s.media_url AS mediaUrl,s.media_kind AS mediaKind,s.theme,s.created,s.expires,m.username,COALESCE(p.avatar,'') AS avatar FROM fan_stories s JOIN members m ON m.id=s.member_id LEFT JOIN fan_profiles p ON p.member_id=m.id WHERE s.deleted=0 AND s.expires>? AND (?='' OR m.username=?) ORDER BY s.created DESC LIMIT 80`).bind(now,username,username).all();return Response.json({stories:rows.results},{headers:{'Cache-Control':'no-store'}})}
export async function POST(req:Request){if(!sameOrigin(req))return Response.json({error:'İstek doğrulanamadı.'},{status:403});const m=await memberSession(req);if(!m)return Response.json({error:'Hikâye için üye olmalısın.'},{status:401});let d:Record<string,unknown>;try{d=await req.json()}catch{return Response.json({error:'Geçersiz istek.'},{status:400})}const body=typeof d.body==='string'?d.body.normalize('NFC').trim():'',mediaUrl=String(d.mediaUrl??''),kind=mediaUrl.endsWith('.jpg')?'photo':mediaUrl.match(/\.(mp4|webm)$/)?'video':'text',theme=['dark','lime','violet'].includes(String(d.theme))?String(d.theme):'dark';if(body.length>500||(!body&&!mediaUrl)||(mediaUrl&&!media.test(mediaUrl)))return Response.json({error:'Hikâyeye kısa yazı veya medya ekle.'},{status:400});const now=Date.now(),id=randomUUID();await channelDb().prepare('INSERT INTO fan_stories(id,member_id,body,media_url,media_kind,theme,created,expires) VALUES(?,?,?,?,?,?,?,?)').bind(id,m.id,body,mediaUrl,kind,theme,now,now+86400000).run();return Response.json({id,expires:now+86400000},{status:201})}
export async function DELETE(req:Request){if(!sameOrigin(req))return Response.json({error:'İstek doğrulanamadı.'},{status:403});const m=await memberSession(req);if(!m)return Response.json({error:'Üye olmalısın.'},{status:401});let d:Record<string,unknown>;try{d=await req.json()}catch{return Response.json({error:'Geçersiz istek.'},{status:400})}const result=await channelDb().prepare('UPDATE fan_stories SET deleted=1 WHERE id=? AND member_id=?').bind(String(d.id),m.id).run();return Response.json({ok:!!result.changes},{status:result.changes?200:404})}
