import Link from 'next/link';
import EditorialText from './editorial-text';
import catalog from '@/lib/semicenk-catalog.json';
import {MediaCredit} from './artist-photo';
import Engagement from './engagement';
import StatsBadge from './stats-badge';
import ViewOnScreen from './view-on-screen';
import CardRail from './card-rail';
import {songSlug} from '@/lib/song-slug';
import {ArrowUpRight,CalendarDays,Disc3,Newspaper,MapPin} from 'lucide-react';
import {dateLabel,entryHref,entryLabels,type Entry,type EntryKind} from '@/lib/entries-types';
function Card({entry:e}:{entry:Entry}){return <article className={'entry-card entry-'+e.kind}><ViewOnScreen target={'entry:'+e.id}/>
 {e.cover&&<Link className="cover-link" href={entryHref(e)} aria-label={e.title+' sayfasını aç'}><img className="entry-cover" src={e.cover} alt={e.title} loading="lazy" referrerPolicy="no-referrer"/><StatsBadge target={'entry:'+e.id}/></Link>}
 <div className="entry-card-inner"><p className="eyebrow">{dateLabel(e.date)}{e.time?' · '+e.time+' (TR)':''}</p><h3><Link href={entryHref(e)}>{e.title}</Link></h3>{e.kind==='konserler'&&<p className="entry-location"><MapPin size={15}/>{e.city} · {e.venue}</p>}{e.summary&&<p>{e.summary}</p>}<Link className="world-link" href={entryHref(e)}>{e.kind==='konserler'?'Konser detayları':e.kind==='albumler'?'Yayını keşfet':'Haberi oku'} <ArrowUpRight size={18}/></Link></div>
 </article>}
function Empty({kind}:{kind:EntryKind}){const Icon=kind==='konserler'?CalendarDays:kind==='albumler'?Disc3:Newspaper;return <div className="entries-empty"><Icon size={28}/><h3>{kind==='konserler'?'Yeni konserleri burada takip et.':kind==='albumler'?'Diskografi burada büyüyecek.':'Yeni gelişmeler burada buluşacak.'}</h3><p>{kind==='konserler'?'Doğrulanmış konser tarihleri eklendiğinde şehir, mekân ve bilet bilgileri burada görünecek.':kind==='albumler'?'Albümler, çıkış tarihleri, şarkı listeleri ve dinleme bağlantıları eklenecek.':'Kaynakları doğrulanan haberler yayınlandıkça burada yer alacak.'}</p></div>}
export function EntriesSection({kind,entries,today}:{kind:EntryKind;entries:Entry[];today:string}){
 const filtered=entries.filter(e=>e.kind===kind);
 const upcoming=filtered.filter(e=>e.date>=today).sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));
 const past=filtered.filter(e=>e.date<today);
 return <section className="entries-section"><p className="eyebrow">SANATÇIDAN GELİŞMELER</p><h2>{kind==='albumler'&&filtered.some(e=>e.artist==='semicenk')?'Diskografi: albümler, EP’ler ve single’lar':entryLabels[kind]}</h2>{!filtered.length?<Empty kind={kind}/>:kind==='konserler'?<><h3 className="entries-subtitle">Yaklaşan konserler</h3>{upcoming.length?<CardRail label="Yaklaşan konserler">{upcoming.map(e=><Card key={e.id} entry={e}/>)}</CardRail>:<p className="entries-note">Şu anda listelenen yaklaşan konser yok.</p>}{past.length>0&&<><h3 className="entries-subtitle">Geçmiş konserler</h3><CardRail label="Geçmiş konserler">{past.map(e=><Card key={e.id} entry={e}/>)}</CardRail></>}</>:<CardRail label={entryLabels[kind]}>{filtered.map(e=><Card key={e.id} entry={e}/>)}</CardRail>}</section>
}
export function EntryDetail({entry:e,today}:{entry:Entry;today:string}){return <article className="entry-detail"><Link className="back" href={'/'+e.artist+'/'+e.kind}>← {entryLabels[e.kind]}</Link><p className="eyebrow">{e.artist==='semicenk'&&e.kind==='haberler'?'MÜZİK YAYINI · ':''}{dateLabel(e.date)}{e.kind==='konserler'&&e.date<today?' · GEÇMİŞ KONSER':''}</p><h2>{e.title}</h2>{e.summary&&<p className="entry-lead">{e.summary}</p>}{e.cover&&<div className="detail-cover"><img className="entry-detail-cover" src={e.cover} alt={e.title} referrerPolicy="no-referrer"/><StatsBadge target={'entry:'+e.id}/></div>}{e.cover&&(e.kind==='konserler'?<MediaCredit artist={e.artist}/>:<p className="credit">Albüm kapağı · <a href={e.source} target="_blank" rel="noreferrer">Apple Music / hak sahibi</a></p>)}{e.kind==='konserler'&&<dl className="concert-facts"><div><dt>Şehir</dt><dd>{e.city}</dd></div><div><dt>Mekân</dt><dd>{e.venue}</dd></div><div><dt>Saat</dt><dd>{e.time?e.time+' (Türkiye saati)':'Henüz belirtilmedi'}</dd></div></dl>}{e.body&&<EditorialText text={e.body}/>}{e.kind==='albumler'&&e.tracks&&<section className="track-list"><h3>Şarkı listesi</h3><ol>{e.tracks.split('\n').filter(Boolean).map((track,i)=><li key={i}><Link href={'/'+e.artist+'/sarkilar/'+songSlug(track)}>{track} →</Link></li>)}</ol></section>}{e.url&&<a className="primary" href={e.url} target="_blank" rel="noopener noreferrer">{e.kind==='konserler'?(e.date<today?'Etkinlik kaynağı':'Bilet / etkinlik sayfası'):e.kind==='albumler'?'Dinleme bağlantısı':'İlgili bağlantı'} <ArrowUpRight size={18}/></a>}{e.source&&<p className="entry-source"><a href={e.source} target="_blank" rel="noopener noreferrer">Kaynağı görüntüle ↗</a></p>}{e.kind==='konserler'&&<p className="entries-note">Tarih ve program değişiklikleri için organizatörün güncel duyurusunu kontrol et.</p>}{e.artist==='semicenk'&&e.kind==='haberler'&&<section className="editorial-related"><h3>İlgili müzik yayını</h3>{catalog.releases.filter(r=>r.url===e.source).map(r=><Link key={r.id} href={'/semicenk/albumler/'+r.slug}>{r.title} · Şarkı listesi ve dinleme bağlantısı →</Link>)}<p><a href="https://evarecords.com.tr/projeler" target="_blank" rel="noreferrer">Eva Records resmî video arşivi ↗</a></p>{e.slug==='tek-yurek-milli-takima-destek'&&<a href="https://www.sozmuzik.com/semicenk-tek-yurek/" target="_blank" rel="noreferrer">Haber kaynağı: Söz Müzik, 1 Haziran 2026 ↗</a>}</section>}<Engagement target={'entry:'+e.id}/></article>}
export function EntryHighlights({artist,entries,today}:{artist:string;entries:Entry[];today:string}){return <section className="entry-highlights" aria-label="Sanatçı gündemi">{(['haberler','konserler','albumler'] as EntryKind[]).map(kind=>{const list=entries.filter(e=>e.kind===kind&&(kind!=='konserler'||e.date>=today));if(kind==='konserler')list.sort((a,b)=>a.date.localeCompare(b.date)||a.time.localeCompare(b.time));const e=list[0];return <div key={kind} className="highlight-card"><p className="eyebrow">{kind==='haberler'?'SON HABER':kind==='konserler'?'YAKLAŞAN KONSER':'ALBÜMLER'}</p><h3>{e?<Link href={entryHref(e)}>{e.title}</Link>:kind==='haberler'?'Gündemi kaçırma.':kind==='konserler'?'Bir sonraki buluşma.':'Müzik yolculuğunu keşfet.'}</h3><p>{e?dateLabel(e.date)+(e.city?' · '+e.city:''):kind==='konserler'?'Doğrulanmış tarihler eklendiğinde burada.':'İçerik seçkisi hazırlanıyor.'}</p><Link className="world-link" href={'/'+artist+'/'+kind}>{entryLabels[kind]} <ArrowUpRight size={17}/></Link></div>})}</section>}

