'use client';
import {useState} from 'react';
import {MoreHorizontal,Flag,Shield,Trash2,VolumeX} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {toast} from 'sonner';
export type ModData={reports:{id:string;message_id:string;reason:string;created:number;name:string;body:string;deleted_at:number|null}[];mutes:{guest_id:string;name:string;until:number;reason:string}[];audit:{action:string;target:string;reason:string;created:number}[]};
type Target={action:'report'|'delete'|'mute'|'unmute'|'resolve';messageId?:string;guestId?:string;reportId?:string};
export function MessageMenu({id,deleted,moderator,onAction}:{id:string;deleted:boolean;moderator:boolean;onAction:(t:Target)=>void}){if(deleted)return null;return <DropdownMenu><DropdownMenuTrigger asChild><button className="message-menu" aria-label="Mesaj işlemleri"><MoreHorizontal size={18}/></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>onAction({action:'report',messageId:id})}><Flag/> Raporla</DropdownMenuItem>{moderator&&<><DropdownMenuItem onSelect={()=>onAction({action:'delete',messageId:id})}><Trash2/> Mesajı kaldır</DropdownMenuItem><DropdownMenuItem onSelect={()=>onAction({action:'mute',messageId:id})}><VolumeX/> 15 dakika sustur</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu>}
export function useChannelActions(){return useState<Target|null>(null)}
export default function ChannelTools({endpoint,guest,moderator,data,reload,target,setTarget}:{endpoint:string;guest:string;moderator:boolean;data:ModData|null;reload:()=>Promise<void>;target:Target|null;setTarget:(t:Target|null)=>void}){
 const [panel,setPanel]=useState(false),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const labels={report:'Mesajı raporla',delete:'Mesajı kaldır',mute:'Misafiri 15 dakika sustur',unmute:'Susturmayı kaldır',resolve:'Raporu kapat'};
 async function submit(payload:Record<string,unknown>){setBusy(true);setError('');try{const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||'İşlem tamamlanamadı.');setTarget(null);setReason('');toast.success(payload.action==='report'?'Raporun moderatöre iletildi.':'İşlem kaydedildi.');await reload();}catch(e){setError(e instanceof Error?e.message:'Yeniden deneyebilirsin.')}finally{setBusy(false)}}
 function choose(t:Target){setPanel(false);setError('');setReason('');setTarget(t)}
 const actionForm=<><label className="tool-label">{target?.action==='report'?'Neden raporluyorsun?':'İşlem gerekçesi'}<textarea autoFocus maxLength={500} minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Kısaca açıkla…"/></label>{error&&<p className="tool-error" role="alert">{error}</p>}<div className="tool-buttons"><button className="secondary" disabled={busy} onClick={()=>{setTarget(null);setReason('');setError('')}}>Vazgeç</button><button className="primary" disabled={busy||reason.trim().length<5} onClick={()=>target&&void submit({...target,reason})}>{busy?'Kaydediliyor…':target?.action==='report'?'Raporu gönder':'Uygula'}</button></div></>;
 return <>{moderator&&<div className="channel-toolbar"><button className="moderation-button" onClick={()=>setPanel(true)}><Shield size={15}/> Moderasyon {data?.reports.length?`(${data.reports.length})`:''}</button></div>}
 <Dialog open={panel&&moderator} onOpenChange={setPanel}><DialogContent className="moderation-dialog"><DialogTitle>Kanal moderasyonu</DialogTitle><DialogDescription>Raporları değerlendir, susturmaları yönet. İşlemler gerekçeleriyle kaydedilir.</DialogDescription><div className="moderation-scroll"><h3>Açık raporlar</h3>{!data?.reports.length&&<p className="moderation-empty">Bekleyen rapor yok.</p>}{data?.reports.map(r=><article className="moderation-report" key={r.id}><strong>{r.name}</strong><blockquote>{r.body}</blockquote><p>Rapor: {r.reason}</p><div className="moderation-actions"><button onClick={()=>choose({action:'delete',messageId:r.message_id})}>Mesajı kaldır</button><button onClick={()=>choose({action:'mute',messageId:r.message_id})}>15 dk sustur</button><button onClick={()=>choose({action:'resolve',reportId:r.id})}>Raporu kapat</button></div></article>)}<h3>Aktif susturmalar</h3>{!data?.mutes.length&&<p className="moderation-empty">Susturulan misafir yok.</p>}{data?.mutes.map(m=><article className="moderation-report" key={m.guest_id}><strong>{m.name}</strong><p>{m.reason}</p><small>Bitiş: {new Date(m.until).toLocaleTimeString('tr-TR')}</small><button className="moderation-link" onClick={()=>choose({action:'unmute',guestId:m.guest_id})}>Susturmayı kaldır</button></article>)}<h3>Son işlemler</h3>{!data?.audit.length&&<p className="moderation-empty">Henüz işlem yapılmadı.</p>}{data?.audit.map((a,i)=><article className="audit-row" key={i}><strong>{labels[a.action as keyof typeof labels]??a.action}</strong><p>{a.reason}</p><small>{new Date(a.created).toLocaleString('tr-TR')}</small></article>)}</div></DialogContent></Dialog>
 <Dialog open={!!target&&target.action!=='delete'} onOpenChange={v=>{if(!v&&!busy){setTarget(null);setReason('');setError('')}}}><DialogContent><DialogTitle>{target?labels[target.action]:''}</DialogTitle><DialogDescription>{target?.action==='mute'?'Bu misafir 15 dakika boyunca yalnızca bu kanala mesaj gönderemez.':target?.action==='report'?'Açıklaman yalnızca moderatörlere gösterilir.':'İşlem gerekçesi moderasyon günlüğüne kaydedilir.'}</DialogDescription>{actionForm}</DialogContent></Dialog>
 <AlertDialog open={target?.action==='delete'} onOpenChange={v=>{if(!v&&!busy){setTarget(null);setReason('');setError('')}}}><AlertDialogContent><AlertDialogTitle>Mesaj kanaldan kaldırılsın mı?</AlertDialogTitle><AlertDialogDescription>İçeriği diğer misafirlerden gizlenecek; yerine kaldırılma bilgisi gösterilecek. İşlem moderasyon günlüğünde tutulacak.</AlertDialogDescription>{actionForm}</AlertDialogContent></AlertDialog>
 </>
}
