'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {Dialog} from 'radix-ui';
import {ChevronDown,Share2,MessageCircle} from 'lucide-react';
import {artists} from '@/lib/artists';
import {artistMedia} from './artist-photo';
import ArtistChannel from './artist-channel';
import MobileNav from './mobile-nav';
type Channel={id:string;name:string;genre:string;participants:number;messages:number;online:number};
export default function ChatLobby(){
 const params=useSearchParams(),[channels,setChannels]=useState<Channel[]>([]),[selected,setSelected]=useState(''),[open,setOpen]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState('');
 const grip=useRef<number|null>(null),lastTrigger=useRef<HTMLButtonElement|null>(null);
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/channels',{cache:'no-store'});if(!r.ok)throw Error();const data=await r.json();setChannels(data.channels);setError('')}catch{setError('Kanallar yüklenemedi. Yeniden dene.')}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh()},30000);return()=>clearInterval(timer)},[refresh]);
 useEffect(()=>{const id=params.get('kanal');if(id&&artists.some(a=>a.id===id)){setSelected(id);setOpen(true)}},[params]);
 const artist=artists.find(a=>a.id===selected);
 async function share(id:string,name:string){const url=location.origin+'/sohbetler?kanal='+encodeURIComponent(id);try{if(navigator.share)await navigator.share({title:name+' fan sohbeti',text:name+' kanalında buluşalım!',url});else{await navigator.clipboard.writeText(url);setNotice(name+' davet bağlantısı kopyalandı.')}}catch(e){if(!(e instanceof DOMException&&e.name==='AbortError'))setNotice('Davet bağlantısı: '+url)}}
 return <><main className="social-page chat-lobby"><p className="eyebrow">FAN TOPLULUKLARI</p><h1>Sohbetler</h1><p className="lobby-intro">Kanalını bul, sohbeti büyüt.</p><p>Arkadaşlarını davet et, sevdiğin sanatçının fanlarıyla buluş.</p><div className="lobby-heading"><h2>En aktif kanallar</h2><span>Son 24 saat · 30 saniyede yenilenir</span></div><p className="ranking-note">Sıralama önce mesaj yazan farklı katılımcı sayısına, sonra mesaj sayısına ve çevrimiçi katılımcılara göre yapılır.</p><label className="channel-search">Kanal ara<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Sanatçı adı…"/></label>{error&&<p role="alert">{error} <button onClick={()=>void refresh()}>Yeniden dene</button></p>}<ol className="channel-ranking">{channels.map((channel,index)=>({channel,index})).filter(({channel})=>channel.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).map(({channel:c,index})=><li key={c.id}><button className="channel-open" onClick={e=>{lastTrigger.current=e.currentTarget;setSelected(c.id);setOpen(true)}} aria-label={c.name+' sohbetini aç'}><span className="channel-rank">{String(index+1).padStart(2,'0')}</span><img src={artistMedia[c.id]?.src} alt=""/><span className="channel-summary"><strong>{c.name}</strong><small>{c.participants} aktif katılımcı · {c.messages} mesaj</small><small className="channel-online">{c.online} kişi çevrimiçi</small></span><MessageCircle aria-hidden="true"/></button><button className="channel-share" onClick={()=>void share(c.id,c.name)} aria-label={c.name+' kanalını paylaş'}><Share2 size={18}/><span>Davet et</span></button></li>)}</ol>{!error&&!channels.length&&<p>Kanallar yükleniyor…</p>}{query&&channels.length>0&&!channels.some(c=>c.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')))&&<p>Bu isimde kanal bulunamadı.</p>}<p role="status" className="share-notice">{notice}</p></main>
 {artist&&!open&&<button className="minimized-channel" onClick={()=>setOpen(true)}><MessageCircle size={20}/>{artist.name} sohbetine dön ↑</button>}
 <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Portal><Dialog.Overlay className="lobby-overlay"/><Dialog.Content className="lobby-channel-dialog" aria-describedby={undefined} onCloseAutoFocus={e=>{e.preventDefault();lastTrigger.current?.focus()}}><div className="lobby-channel-toolbar" onTouchStart={e=>{grip.current=e.touches[0].clientY}} onTouchEnd={e=>{if(grip.current!==null&&e.changedTouches[0].clientY-grip.current>65)setOpen(false);grip.current=null}}><Dialog.Title>{artist?.name} sohbeti</Dialog.Title><button onClick={()=>artist&&void share(artist.id,artist.name)} aria-label="Kanalı paylaş"><Share2 size={20}/></button><Dialog.Close aria-label="Sohbeti küçült"><ChevronDown/>Küçült</Dialog.Close></div>{artist&&<ArtistChannel key={artist.id} artist={artist.id} name={artist.name} fullscreen/>}<p className="lobby-share-status" role="status">{notice}</p></Dialog.Content></Dialog.Portal></Dialog.Root><MobileNav active="chat"/></>
}
