'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {Eye,Heart,MessageCircle,X} from 'lucide-react';
type Member={id:string;username:string};
type Comment={id:string;body:string;created:number;username:string;mine:number;likes:number;liked:number};
type Data={likes:number;liked:boolean;comments:Comment[];commentCount:number;member:Member|null};
export default function Engagement({target,follow}:{target:string;follow?:{count:number;followed:boolean;toggle:()=>void}}){
 const [mounted,setMounted]=useState(false),[dismissed,setDismissed]=useState(false),[data,setData]=useState<Data|null>(null),[views,setViews]=useState(0),[open,setOpen]=useState(false),[gate,setGate]=useState(false),[mode,setMode]=useState<'register'|'login'>('register'),[sort,setSort]=useState<'popular'|'new'>('popular');
 const [name,setName]=useState(''),[password,setPassword]=useState(''),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const startY=useRef<number|null>(null),commentRef=useRef<HTMLTextAreaElement>(null);
 const load=useCallback(async()=>{try{const [r,s]=await Promise.all([fetch('/api/engagement?target='+encodeURIComponent(target)+'&sort='+sort,{cache:'no-store'}),fetch('/api/engagement/stats?targets='+encodeURIComponent(target),{cache:'no-store'})]);if(r.ok){const v=await r.json();setData(v);const count=s.ok?(await s.json()).stats?.[target]?.views??0:0;setViews(count);document.dispatchEvent(new CustomEvent('fans:stats',{detail:{target,likes:v.likes,comments:v.commentCount,views:count}}))}}catch{}},[target,sort]);
 useEffect(()=>{setMounted(true);void fetch('/api/views',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target})}).then(()=>load()).catch(()=>load())},[target]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!open&&!gate)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){if(gate)setGate(false);else setOpen(false)}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open,gate]);
 useEffect(()=>{document.body.classList.toggle('fans-comments-open',open);return()=>document.body.classList.remove('fans-comments-open')},[open]);
 async function act(action:'like'|'comment'){
  if(!data?.member){setGate(true);setError('Beğenmek veya yorum yazmak için üye olman gerekiyor.');return}
  setBusy(true);setError('');try{const r=await fetch('/api/engagement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target,action,body})});const v=await r.json();if(!r.ok){if(r.status===401)setGate(true);setError(v.error??'İşlem tamamlanamadı.')}else{if(action==='comment')setBody('');await load()}}catch{setError('Bağlantıyı kontrol edip tekrar dene.')}finally{setBusy(false)}
 }
 async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/member/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:mode,username:name,password})});const v=await r.json();if(!r.ok)setError(v.error??'İşlem tamamlanamadı.');else{setPassword('');setGate(false);await load();if(open)setTimeout(()=>commentRef.current?.focus(),100)}}catch{setError('Bağlantıyı kontrol edip tekrar dene.')}finally{setBusy(false)}}
 async function remove(id:string){setBusy(true);try{const r=await fetch('/api/engagement',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});if(r.ok)await load()}finally{setBusy(false)}}
 async function likeComment(id:string){if(!data?.member){setGate(true);setError('Yorumu beğenmek için üye olman gerekiyor.');return}setBusy(true);try{const r=await fetch('/api/engagement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({target,action:'comment_like',commentId:id})});if(r.ok)await load()}finally{setBusy(false)}}
 async function logout(){await fetch('/api/member/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});await load()}
 const dock=dismissed?<button className="engagement-restore" onClick={()=>setDismissed(false)} aria-label="Etkileşim kutusunu yeniden aç"><Heart size={18}/></button>:<div className="engagement-dock" aria-label="İçerik etkileşimi"><button className="engagement-dismiss" aria-label="Etkileşim kutusunu kapat" onClick={()=>setDismissed(true)}><X size={15}/></button><span className="dock-views"><Eye size={18}/>{views} görüntülenme</span><button onClick={()=>void act('like')} disabled={busy} aria-pressed={!!data?.liked}><Heart size={20} fill={data?.liked?'currentColor':'none'}/>{data?.likes??0} beğeni</button><button onClick={()=>setOpen(true)}><MessageCircle size={20}/>{data?.commentCount??0} yorum</button>{follow&&<button className="dock-follow" onClick={follow.toggle}>{follow.followed?'Takiptesin':'Takip et'} · {follow.count}</button>}</div>;
 const sheet=<div className="comments-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><section className="comments-sheet" role="dialog" aria-modal="true" aria-label="Yorumlar"><div className="sheet-handle" onClick={()=>setOpen(false)} onTouchStart={e=>{startY.current=e.touches[0].clientY}} onTouchEnd={e=>{if(startY.current!==null&&e.changedTouches[0].clientY-startY.current>70)setOpen(false);startY.current=null}} aria-hidden="true"/><div className="sheet-header"><h2>Yorumlar ({data?.commentCount??0})</h2><button aria-label="Yorumları kapat" onClick={()=>setOpen(false)}><X size={21}/></button></div><div className="comment-sort" aria-label="Yorum sıralaması"><button aria-pressed={sort==='popular'} onClick={()=>setSort('popular')}>En beğenilenler</button><button aria-pressed={sort==='new'} onClick={()=>setSort('new')}>En yeniler</button></div><div className="comments-sheet-scroll"><div className="comments">{data?.comments.length?data.comments.map(c=><article key={c.id}><strong>{c.username}</strong><time dateTime={new Date(c.created).toISOString()}>{new Date(c.created).toLocaleDateString('tr-TR')}</time><p>{c.body}</p><button className="comment-like" aria-pressed={!!c.liked} disabled={busy} onClick={()=>void likeComment(c.id)}><Heart size={15} fill={c.liked?'currentColor':'none'}/>{c.likes} beğeni</button>{c.mine===1&&<button className="comment-delete" disabled={busy} onClick={()=>void remove(c.id)}>Yorumu sil</button>}</article>):<p>Henüz yorum yok. İlk yorumu sen yazabilirsin.</p>}</div></div><form className="sheet-composer" onSubmit={e=>{e.preventDefault();void act('comment')}}><textarea ref={commentRef} aria-label="Yorumunu yaz" maxLength={600} value={body} onChange={e=>setBody(e.target.value)} placeholder="Yorum yaz…" onFocus={()=>{if(!data?.member){setGate(true);setError('Yorum yazmak için üye olman gerekiyor.')}}}/><button type="submit" disabled={busy||!body.trim()}>Gönder</button></form>{error&&!gate&&<p className="engagement-error" role="status">{error}</p>}{data?.member?<div className="sheet-member"><span>{data.member.username}</span><button onClick={logout}>Çıkış yap</button></div>:<button className="sheet-login" onClick={()=>{setGate(true);setError('')}}>Üye ol / Giriş yap</button>}</section></div>;
 const loginDialog=<div className="member-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setGate(false)}}><div role="dialog" aria-modal="true" aria-labelledby="member-title" className="member-dialog"><button className="member-close" aria-label="Kapat" onClick={()=>setGate(false)}><X size={20}/></button><p className="eyebrow">FANS TOPLULUĞU</p><h2 id="member-title">Beğenmek ve yorum yazmak için üye ol.</h2><p>Sanatçı sohbetine misafir olarak katılmaya devam edebilirsin. Beğeni ve yorumlar hesabına bağlıdır.</p><div className="member-modes"><button aria-pressed={mode==='register'} onClick={()=>{setMode('register');setError('')}}>Üye ol</button><button aria-pressed={mode==='login'} onClick={()=>{setMode('login');setError('')}}>Giriş yap</button></div><form onSubmit={login}><label>Kullanıcı adı<input autoFocus autoComplete="username" required minLength={3} maxLength={24} value={name} onChange={e=>setName(e.target.value)}/></label><label>Şifre<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} required minLength={10} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="engagement-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{mode==='register'?'Hesap oluştur':'Giriş yap'}</button></form></div></div>;
 return <section className="engagement" aria-label="Beğeni ve yorumlar">{mounted&&createPortal(<>{dock}{open&&sheet}{gate&&loginDialog}</>,document.body)}</section>;
}
