'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Video,Mic,SwitchCamera,X,Square} from 'lucide-react';
export default function FanCamera({onMedia,onClose}:{onMedia:(v:{url:string;kind:'photo'|'video'})=>void;onClose:()=>void}){
 const preview=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),cancelled=useRef(false);
 const [facing,setFacing]=useState<'user'|'environment'>('user'),[ready,setReady]=useState(false),[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 function stopTracks(){stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(preview.current)preview.current.srcObject=null;setReady(false)}
 useEffect(()=>()=>{cancelled.current=true;if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop())},[]);
 async function openCamera(next:'user'|'environment'=facing){setError('');stopTracks();if(!navigator.mediaDevices?.getUserMedia){setError('Kamera için güvenli bağlantı ve desteklenen tarayıcı gerekiyor.');return}try{const value=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:next},width:{ideal:720},height:{ideal:1280}},audio:{echoCancellation:true}});stream.current=value;if(preview.current){preview.current.srcObject=value;await preview.current.play().catch(()=>{})}setReady(true)}catch{try{const value=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:next}},audio:false});stream.current=value;if(preview.current){preview.current.srcObject=value;await preview.current.play().catch(()=>{})}setReady(true);setError('Mikrofon izni yok; fotoğraf veya sessiz video çekebilirsin.')}catch{setError('Kamera izni verilmedi. Tarayıcı ayarından izin verebilirsin.')}}}
 async function upload(file:File){setBusy(true);setError('');try{if(file.size>18_000_000)throw new Error('Video 18 MB sınırını aştı. Daha kısa kayıt yap.');const form=new FormData();form.set('file',file);const r=await fetch('/api/social/media',{method:'POST',body:form});const v=await r.json();if(!r.ok)throw new Error(v.error||'Medya yüklenemedi.');onMedia({url:v.url,kind:v.kind});stopTracks();onClose()}catch(e){setError(e instanceof Error?e.message:'Yükleme başarısız.')}finally{setBusy(false)}}
 function capture(){const video=preview.current;if(!video||!video.videoWidth)return;const canvas=document.createElement('canvas'),scale=Math.min(1,1080/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d')?.drawImage(video,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob)void upload(new File([blob],'kamera.jpg',{type:'image/jpeg'}))},'image/jpeg',.82)}
 function record(){cancelled.current=false;if(recorder.current?.state==='recording'){recorder.current.stop();return}if(!stream.current||typeof MediaRecorder==='undefined'){setError('Bu tarayıcıda video kaydı desteklenmiyor. Dosya seçebilirsin.');return}const mime=['video/mp4','video/webm'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime){setError('Bu tarayıcı uygun video biçiminde kayıt yapamıyor.');return}try{const chunks:Blob[]=[];const instance=new MediaRecorder(stream.current,{mimeType:mime,videoBitsPerSecond:2_000_000,audioBitsPerSecond:96_000});recorder.current=instance;instance.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};instance.onstop=()=>{setRecording(false);if(timer.current)clearTimeout(timer.current);const file=new File(chunks,mime==='video/mp4'?'kamera.mp4':'kamera.webm',{type:mime});if(file.size&&!cancelled.current)void upload(file)};instance.start(1000);setRecording(true);timer.current=setTimeout(()=>{if(instance.state==='recording')instance.stop()},30000)}catch{setError('Kayıt başlatılamadı. Dosya yüklemeyi deneyebilirsin.')}}
 return <div className="camera-overlay" role="dialog" aria-modal="true" aria-label="Kamera ile paylaşım"><div className="camera-panel"><div className="camera-title"><span><Camera size={20}/> Kamera ile paylaş</span><button onClick={()=>{cancelled.current=true;if(recorder.current?.state==='recording')recorder.current.stop();stopTracks();onClose()}} aria-label="Kamerayı kapat"><X/></button></div><div className="camera-stage"><video ref={preview} autoPlay muted playsInline/>{!ready&&<div><Camera size={38}/><p>Kamera ve mikrofon izniyle fotoğraf veya kısa video çekebilirsin.</p><button className="primary" onClick={()=>void openCamera()}>Kamerayı aç</button></div>}{recording&&<span className="recording-chip">● Kayıt sürüyor · en çok 30 saniye</span>}</div><div className="camera-actions"><button onClick={capture} disabled={!ready||recording||busy}><Camera size={19}/> Fotoğraf</button><button onClick={record} disabled={!ready||busy}>{recording?<Square size={18}/>:<Video size={19}/>} {recording?'Kaydı bitir':'Video çek'}</button><button onClick={()=>{const next=facing==='user'?'environment':'user';setFacing(next);void openCamera(next)}} disabled={!ready||recording||busy} aria-label="Kamerayı çevir"><SwitchCamera size={19}/></button></div><p className="camera-hint"><Mic size={15}/> Video için mikrofon sesi de kaydedilir. Kayıt yalnızca paylaşımı seçince yüklenir.</p>{error&&<p className="social-error" role="alert">{error}</p>}</div></div>
}
