'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {artists} from '@/lib/artists';
import {artistMedia} from './artist-photo';
export default function ProfileFollowing(){
 const [ids,setIds]=useState<string[]>([]),[fans,setFans]=useState<Array<{username:string;avatar:string}>>([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[loaded,setLoaded]=useState(false);
 const reload=useCallback(async()=>{try{const [ar,fr]=await Promise.all([fetch('/api/follows',{cache:'no-store'}),fetch('/api/social/follow',{cache:'no-store'})]);if(!ar.ok||(!fr.ok&&fr.status!==401))throw Error();const a=await ar.json(),f=fr.ok?await fr.json():{};setIds(a.followed??[]);setFans(f.members??[]);setLoaded(true);setError('')}catch{setError('Takiplerin yüklenemedi. Yeniden dene.')}},[]);
 useEffect(()=>{void reload()},[reload]);
 async function remove(kind:'artist'|'fan',id:string){setBusy(kind+id);setError('');try{const r=await fetch(kind==='artist'?'/api/follows':'/api/social/follow',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(kind==='artist'?{action:'remove',artist:id}:{action:'remove',username:id})});if(!r.ok)throw Error();if(kind==='artist'){const v=await r.json();setIds(v.followed??[]);try{localStorage.setItem('fans.followed.v1',JSON.stringify(v.followed??[]))}catch{}}else setFans(v=>v.filter(f=>f.username!==id));}catch{setError('Takip kaldırılamadı. Yeniden dene.')}finally{setBusy('')}}
 return <section className="profile-following" id="takipler"><h2>Takip ettiklerin</h2><p>Sanatçılarını ve fan arkadaşlarını buradan yönet.</p>{error&&<p role="alert">{error} <button onClick={()=>void reload()}>Yenile</button></p>}<h3>Sanatçılar</h3><div className="profile-follow-grid">{ids.map(id=>{const a=artists.find(a=>a.id===id);return a&&<div key={id}><Link href={'/'+id}><img src={artistMedia[id]?.src} alt=""/><strong>{a.name}</strong></Link><button disabled={!!busy} onClick={()=>void remove('artist',id)} aria-label={a.name+' takibini bırak'}>Takibi bırak</button></div>})}</div>{loaded&&!ids.length&&<p>Henüz sanatçı takip etmiyorsun. <Link href="/">Sanatçıları keşfet →</Link></p>}<h3>Fanlar</h3><div className="profile-follow-grid">{fans.map(f=><div key={f.username}><Link href={'/fanz/'+encodeURIComponent(f.username)}>{f.avatar&&<img src={f.avatar} alt=""/>}<strong>{f.username}</strong></Link><button disabled={!!busy} onClick={()=>void remove('fan',f.username)} aria-label={f.username+' takibini bırak'}>Takibi bırak</button></div>)}</div>{loaded&&!fans.length&&<p>Takip ettiğin fanlar burada görünecek.</p>}</section>
}
