import {isCancelled} from '@/lib/semicenk-events';
import Link from 'next/link';
import CardRail from './card-rail';
import {dateLabel,entryHref,type Entry} from '@/lib/entries-types';
import {entryDisplayTitle} from '@/lib/semicenk-page-seo';
import catalog from '@/lib/semicenk-catalog.json';
export default function SemicenkMediaRows({entries}:{entries:Entry[]}){
 const songs=Object.values(catalog.songs).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);
 return <div className="artist-media-rows editorial-home"><div className="editorial-stats"><Link href="/semicenk/albumler"><strong>{entries.filter(e=>e.kind==='albumler').length}</strong> müzik yayını</Link><Link href="/semicenk/sarkilar"><strong>{Object.keys(catalog.songs).length}</strong> şarkı</Link><Link href="/semicenk/biyografi">Cenk Baş’tan Semicenk’e →</Link></div>{(['haberler','albumler','konserler'] as const).map(kind=><section key={kind}><div className="feed-heading"><div><p className="eyebrow">{kind==='haberler'?'HABER ARŞİVİ':kind==='albumler'?'DİSKOGRAFİ':'SAHNE TAKVİMİ'}</p><h2>{kind==='haberler'?'Semicenk haberleri':kind==='albumler'?'Son albümler, EP’ler ve single’lar':'Yaklaşan konserler'}</h2></div><Link href={'/semicenk/'+kind}>Tümünü gör →</Link></div><CardRail label={'Semicenk '+kind}>{entries.filter(e=>e.kind===kind&&(kind!=='konserler'||(e.date>=new Date().toISOString().slice(0,10)&&!isCancelled(e)))).sort((a,b)=>kind==='konserler'?a.date.localeCompare(b.date):b.date.localeCompare(a.date)).slice(0,6).map(e=><Link href={entryHref(e)} className="artist-media-card" key={e.id}><img src={e.cover} alt={e.title+(kind==='konserler'?' — arşiv fotoğrafı':' — yayın kapağı')} loading="lazy"/><strong>{entryDisplayTitle(e)}</strong><span>{dateLabel(e.date)}{e.city?' · '+e.city:''}</span></Link>)}</CardRail></section>)}<section><div className="feed-heading"><h2>Şarkıları keşfet</h2><Link href="/semicenk/sarkilar">Tüm şarkılar →</Link></div><CardRail label="Semicenk şarkıları">{songs.map(s=><Link className="artist-media-card" key={s.slug} href={'/semicenk/sarkilar/'+s.slug}><img src={s.cover} alt={s.albumTitle+' kapağı'} loading="lazy"/><strong>{s.name}</strong><span>{s.credits}</span></Link>)}</CardRail></section></div>
}
