'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowUpRight,ArrowDownRight,Minus} from 'lucide-react';
import {artists} from '@/lib/artists';
import {artistMedia} from './artist-photo';
import {useArtistMetrics} from './artist-metrics';
import MobileNav from './mobile-nav';
type Metric='engagement'|'views'|'comments';
const labels:{key:Metric;name:string;unit:string}[]=[{key:'engagement',name:'Etkileşim',unit:'etkileşim'},{key:'views',name:'Görüntülenme',unit:'görüntülenme'},{key:'comments',name:'Yorumlar',unit:'yorum'}];
export default function TopLists(){const [metric,setMetric]=useState<Metric>('engagement'),stats=useArtistMetrics(),active=labels.find(x=>x.key===metric)!;const sorted=[...artists].sort((a,b)=>(stats[b.id]?.[metric]??0)-(stats[a.id]?.[metric]??0)||a.name.localeCompare(b.name,'tr'));return <><main className="top-lists"><Link className="back" href="/">← Keşfe dön</Link><p className="eyebrow">FANS TOP LİSTELER</p><h1>Toplulukların nabzı.</h1><p>Yayınlanan içeriklerin gerçek görüntülenme, beğeni ve yorum toplamları.</p><div className="top-tabs">{labels.map(x=><button key={x.key} aria-pressed={metric===x.key} onClick={()=>setMetric(x.key)}>{x.name}</button>)}</div><ol>{sorted.map((a,i)=><li key={a.id}><Link href={'/'+a.id}><span className="top-position">{stats[a.id]?.rank[metric]??i+1}.</span><span className={'top-movement '+(stats[a.id]?.movement?.[metric]??'new')} aria-label={stats[a.id]?.movement?.[metric]==='up'?'Yükseldi':stats[a.id]?.movement?.[metric]==='down'?'Düştü':stats[a.id]?.movement?.[metric]==='same'?'Yerinde kaldı':'Kıyas için önceki gün verisi yok'}>{stats[a.id]?.movement?.[metric]==='up'?<ArrowUpRight size={20}/>:stats[a.id]?.movement?.[metric]==='down'?<ArrowDownRight size={20}/>:<Minus size={20}/>}</span><img src={artistMedia[a.id].src} alt=""/><strong>{a.name}</strong><span className="top-value">{stats[a.id]?.[metric]??0} {active.unit}</span></Link></li>)}</ol><p className="top-legend"><span className="up"><ArrowUpRight size={17}/> Yükseldi</span><span className="down"><ArrowDownRight size={17}/> Düştü</span><span className="same"><Minus size={17}/> Yerinde</span></p><p className="top-note">Sıralama bugünün başlangıcındaki Türkiye saati 00.00 verisiyle karşılaştırılır. Önceki veri yoksa çizgi gösterilir. Etkileşim = içerik beğenileri + yayınlanmış yorumlar. Eşit sonuçlar aynı sırayı paylaşır.</p></main><MobileNav active="top"/></>}
