#!/usr/bin/env python3
"""Source-checked Manifest content as of 2026-09-27; emits a revisioned batch."""
import json,sqlite3,os
from pathlib import Path
DB=os.environ['DATABASE_PATH'];db=sqlite3.connect(DB);db.row_factory=sqlite3.Row
artist='manifest';ops=[];base='/images/albums/manifest.jpg';portrait='/images/artists/manifest.jpg'
apple='https://music.apple.com/us/artist/manifest/1793856618'
original='https://music.apple.com/tr/album/manifestival/1813439256'
deluxe='https://music.apple.com/tr/album/manifestival-deluxe/1836369123'
venue='https://www.ovoarena.co.uk/events/detail/manifest'
bilet='https://www.biletix.com/etkinlik-grup/536572193/TURKIYE/tr/manifestival'
def revision(table,key):
 q={'artist_content':('artist',artist),'artist_entries':('id',key),'artist_songs':('slug',key)}[table]
 row=db.execute(f'SELECT revision FROM {table} WHERE artist=? AND {q[0]}=?',(artist,q[1])).fetchone();return row['revision'] if row else None
def entry(kind,slug,title,date,summary,body,source,**fields):
 id={'manifestival':'real-manifest-albumler','manifestival-yayinda':'real-manifest-haberler','konser-2026-06-06':'real-manifest-konserler'}.get(slug,'manifest-'+kind+'-'+slug)
 v=dict(title=title,date=date,summary=summary,body=body,source=source,url=source,status='published',cover=fields.pop('cover',base if kind=='albumler' else portrait if kind=='konserler' else base),seo_title=fields.pop('seo_title',title+' | Fanz'),seo_description=fields.pop('seo_description',summary),**fields)
 ops.append(dict(type='entry',id=id,kind=kind,slug=slug,expectedRevision=revision('artist_entries',id),values=v));return id
bio='''## Manifest kimdir?
Manifest, 2025 yılında Big5 Türkiye seçmelerinin ardından kurulan altı üyeli bir Türk pop grubudur. Esin Bahat, Hilal Yelekçi, Lidya Pınar, Mina Solak, Sueda Uluca ve Zeynep Sude Oktay; vokal, dans ve koreografiyi birlikte kullanan sahne anlayışıyla tanındı. Grup, ilk şarkısı Zamansızdık ile Şubat 2025’te dinleyiciyle buluştu.

## İlk albüm: manifestival
Zamansızdık, Arıyo, KTS ve Snap yayınları ilk albüme giden yolu açtı. manifestival 13 Haziran 2025’te Hypers Music etiketiyle 11 şarkı olarak yayımlandı. Intro, Manifest, Zehir, Hayır, Yaşanacaksa, Durma ve Outro albümün diğer parçaları arasında. 5 Eylül’de çıkan manifestival (deluxe), beş ek düzenlemeyle toplam 16 parçaya ulaştı. Remiksler ile özgün kayıtları ayrı şarkılar olarak listeliyoruz; bir remiksi yeni bir stüdyo albümü gibi göstermiyoruz.

## 2025–2026 yayınları
2025 sonbaharında RÜYA, Aralık ayında Amatör yayımlandı. 2026’da Başrol Sensin (1. Yıl Özel), Daha İyi, Ajda Pekkan ile Hileli, Toz Pembe ve Motive ile Pango’nun da yer aldığı pVg (Manifest Live Remix) dinleyiciyle buluştu. Yayın tarihleri ve iş birlikleri Apple Music kayıtlarıyla karşılaştırıldı. Albümdeki Yaşanacaksa, Çıtır Kızlar’ın Yaşanacaksa Yaşanacak eserine dayanan yeni bir yorum olarak ayrıca belirtilir.

## Konserler ve sahne
Manifestival Ankara için Biletix, 6–7 Haziran 2026 tarihlerini ve Atatürk Orman Çiftliği’ni duyurdu. OVO Arena Wembley, grubun 16 Ekim 2026 Londra konserini listeliyor. Bu sayfadaki geçmiş konser kaydı etkinliğin gerçekleştiğine dair bağımsız teyit değildir; gelecek etkinlik için saat ve bilet koşullarında organizatörün sayfası geçerlidir.

Bu arşiv bağımsız bir hayran sayfasıdır; grubun resmî hesabı değildir. Kaynaklar 27 Eylül 2026 itibarıyla kontrol edilmiştir.'''
sources='\n'.join([venue,original,deluxe,apple,bilet,'https://www.shazam.com/tr-tr/album/1836369123/manifestival-deluxe'])
ops.append(dict(type='biography',expectedRevision=revision('artist_content',artist),values=dict(biography=bio,sources=sources)))
a1=entry('albumler','manifestival','manifestival', '2025-06-13','Manifest’in 13 Haziran 2025 tarihli ilk albümü; 11 şarkı, yaklaşık 26 dakika.','manifestival, grubun ilk uzunçaları olarak Hypers Music etiketiyle yayımlandı. Albüm Intro ile açılıyor; Snap, KTS, Arıyo, Manifest, Zehir, Hayır, Zamansızdık, Yaşanacaksa, Durma ve Outro ile tamamlanıyor.\n\nŞarkı adları, sıralama ve albüm bilgisi Apple Music ile Shazam kayıtlarında karşılaştırıldı. Zehir kaydında Pango, Manifest kaydında Arem Özgüç ile Arman Aydın birlikte anılıyor. Yaşanacaksa, Çıtır Kızlar’ın eserine dayanan bir yeniden yorumdur. Albüm bağlantısı resmî dinleme sayfasına gider.\n\nKaynak kontrolü: 27 Eylül 2026.',original,tracks='Intro\nSnap\nKTS\nArıyo\nManifest\nZehir\nHayır\nZamansızdık\nYaşanacaksa\nDurma\nOutro',release_name='manifestival',release_format='Albüm',release_credits='Manifest · Hypers Music',seo_title='Manifest manifestival Albümü (2025): 11 Şarkı ve Yayın Bilgileri',seo_description='Manifest’in 13 Haziran 2025’te yayımlanan manifestival albümünü, 11 parçalık şarkı listesini ve resmî dinleme bağlantısını incele.')
a2=entry('albumler','manifestival-deluxe','manifestival (deluxe)','2025-09-05','Manifest’in 5 Eylül 2025 tarihli deluxe albümü; toplam 16 parça.','manifestival (deluxe), ilk albümün 11 şarkısını ve beş ek düzenlemeyi bir araya getiriyor. Yeni sıralamada Rampapapam (Arem Ozguc & Arman Aydin Remix), Arıyo (Zeki Arkun Remix), Zehir (Motive Remix), Hayır (AYDEED Remix) ve Outro (Extended Version) yer alıyor.\n\nBu bir ayrı 16 parçalık sürümdür; önceki albümün 11 parçası yeniden yayımlandığı için katalogda her özgün şarkıyı bir kez gösteriyoruz. Apple Music yayın tarihi, Shazam parça listesi ve MusicBrainz süreleri karşılaştırıldı.\n\nKaynak kontrolü: 27 Eylül 2026.',deluxe,tracks='Intro\nSnap\nKTS\nArıyo\nManifest\nZehir\nHayır\nZamansızdık\nYaşanacaksa\nDurma\nOutro\nRampapapam (Arem Ozguc & Arman Aydin Remix)\nArıyo (Zeki Arkun Remix)\nZehir (Motive Remix)\nHayır (AYDEED Remix)\nOutro (Extended Version)',release_name='manifestival (deluxe)',release_format='Albüm',release_credits='Manifest · Hypers Music',seo_title='Manifest manifestival (deluxe): 16 Şarkı, Remiksler ve Tarih',seo_description='Manifest’in 5 Eylül 2025 tarihli manifestival (deluxe) sürümündeki 16 şarkı, yeni remiksler ve resmî dinleme bağlantısı.')
releases=[
 ('zamansizdik','Zamansızdık','2025-02-07','https://music.apple.com/us/album/zamans%C4%B1zd%C4%B1k-single/1793603953'),
 ('ariyo','Arıyo','2025-04-11','https://music.apple.com/us/album/ar%C4%B1yo-single/1803619028'),
 ('ruya','RÜYA','2025-10-03','https://music.apple.com/us/album/r%C3%BCya-single/1839930351'),
 ('amator','Amatör','2025-12-05','https://music.apple.com/tr/album/amat%C3%B6r-single/1855827116'),
 ('basrol-sensin','Başrol Sensin (1. Yıl Özel)','2026-02-13','https://music.apple.com/tr/album/ba%C5%9Frol-sensin-1-y%C4%B1l-%C3%B6zel-single/1875885663'),
 ('manifest-arem-arman-remix','Manifest (Arem & Arman Remix)','2026-02-27','https://music.apple.com/us/album/manifest-arem-arman-remix-single/1879510798'),
 ('zehir-arem-arman-remix','Zehir (Arem & Arman Remix)','2026-03-06','https://music.apple.com/us/album/zehir-arem-arman-remix-single/1880680385'),
 ('daha-iyi','Daha İyi','2026-04-03','https://music.apple.com/tr/album/daha-i-yi-single/1889304032'),
 ('hileli','Hileli (Ajda Pekkan ile)','2026-05-08','https://music.apple.com/tr/album/hileli-single/1895942716'),
 ('toz-pembe','Toz Pembe','2026-07-03','https://music.apple.com/tr/album/toz-pembe-single/6784751861'),
 ('pvg-manifest-live-remix','pVg (Manifest Live Remix)','2026-07-24','https://music.apple.com/us/album/pvg-manifest-live-remix-single/6793467822'),
]
release_ids={}
for slug,name,date,url in releases:
 credit='Manifest ve Ajda Pekkan' if slug=='hileli' else 'Manifest, Motive ve Pango' if slug.startswith('pvg') else 'Manifest · Hypers Music'
 summary=f'{name}: {date} tarihli single yayını; kaynak Apple Music.'
 body=f'{name}, Apple Music kataloğunda {date} tarihiyle yayımlanan bir single olarak yer alıyor. '+('Ajda Pekkan’ın Manifest ile ortak kaydıdır; iki sanatçının birlikte anılması önemlidir.' if slug=='hileli' else 'Motive ve Pango ile ortak remiks kaydıdır; özgün bir Manifest albümü olarak sunulmaz.' if slug.startswith('pvg') else 'Şarkının resmî dinleme bağlantısı ve doğrulanmış yayın tarihi aşağıdadır.')+'\n\nBu sayfa bir hayran arşivi kaydıdır. Tam sözler yerine künye ve resmî dinleme sayfası verilir.\n\nKaynak kontrolü: 27 Eylül 2026.'
 release_ids[slug]=entry('albumler',slug,name,date,summary,body,url,tracks=name.replace(' (Ajda Pekkan ile)',''),release_name=name,release_format='Single',release_credits=credit,cover=portrait,seo_title=f'Manifest {name} Single: Yayın Tarihi ve Dinleme',seo_description=f'Manifest {name} şarkısının {date} tarihli yayını, sanatçı bilgileri ve resmî Apple Music bağlantısı.')
entry('haberler','manifestival-yayinda','Manifest’in ilk albümü manifestival yayımlandı','2025-06-13','Manifest’in 11 parçalık ilk albümü manifestival, 13 Haziran 2025’te yayımlandı.','Big5 Türkiye sonrasında kurulan Manifest, ilk albümü manifestival ile şarkılarını tek bir yayında topladı. 13 Haziran 2025 tarihli Apple Music kaydı 11 parçadan oluşuyor.\n\nIntro ile başlayan albümde Snap, KTS, Arıyo, Manifest, Zehir, Hayır, Zamansızdık, Yaşanacaksa, Durma ve Outro yer alıyor. Parçaların ayrıntıları Manifest diskografisi ile şarkı sayfalarında bulunabilir.\n\nKaynak kontrolü: 27 Eylül 2026.',original,seo_title='Manifest manifestival Albümü Yayımlandı: 11 Şarkılık İlk Albüm',seo_description='Manifest’in 13 Haziran 2025’te yayımlanan ilk albümü manifestival, 11 şarkılık listesi ve resmî kaynak bilgileriyle arşivde.')
news=[
 ('manifestival-deluxe-yayinda','2025-09-05','Manifest, manifestival albümünün deluxe sürümünü yayımladı','manifestival (deluxe) 16 parçaya çıktı. İlk albüme beş yeni düzenleme eklendi.',deluxe,'Yeni sürüm ilk albümdeki 11 kaydı korurken Rampapapam, Arıyo, Zehir, Hayır ve Outro için farklı düzenlemeler getiriyor. Şarkıların özgün sürümleriyle remiksleri karıştırmamak için diskografide iki albüm sürümü ayrı gösteriliyor.'),
 ('ruya-single-yayinda','2025-10-03','Manifest’ten RÜYA single yayını','RÜYA, 3 Ekim 2025 tarihli Apple Music kaydıyla ayrı bir single olarak yayımlandı.',releases[2][3],'Grubun manifestival sonrasındaki bağımsız şarkılarından RÜYA, 2025 sonbaharındaki yayın takviminde yer alıyor. Dinleme bağlantısı resmî albüm sayfasında; bu kaydı deluxe albümün içine yanlışlıkla eklemiyoruz.'),
 ('amator-single-yayinda','2025-12-05','Manifest’in Amatör şarkısı yayımlandı','Amatör, 5 Aralık 2025’te ayrı single olarak yayımlandı.',releases[3][3],'Apple Music yayını şarkıyı 2025 sonundaki Manifest kataloğuna ayrı bir single olarak ekliyor. Resmî kayıt ile İngilizce Amateur sürümü aynı ad altında karıştırılmamalı.'),
 ('daha-iyi-single-yayinda','2026-04-03','Manifest’in Daha İyi şarkısı 3 Nisan’da yayımlandı','Daha İyi, Manifest’in 3 Nisan 2026 tarihli single kaydıdır.',releases[7][3],'Daha İyi için yayın tarihi ve Hypers Music künyesi Apple Music’te listeleniyor. Şarkıyı manifestival albümüne sonradan eklemek yerine ayrı bir single olarak arşivliyoruz.'),
 ('manifest-ajda-pekkan-hileli','2026-05-08','Manifest ve Ajda Pekkan Hileli’de buluştu','Hileli, Manifest ve Ajda Pekkan’ın ortak 8 Mayıs 2026 tarihli single yayını.',releases[8][3],'Apple Music, Hileli kaydında Manifest ile Ajda Pekkan’ı birlikte sanatçı olarak gösteriyor. Eser yalnızca grubun solo kaydı gibi sunulmamalı. Resmî video ve dinleme bağlantısı kaynağın ilgili sayfasında görülebilir.'),
 ('toz-pembe-single-yayinda','2026-07-03','Manifest, Toz Pembe single’ını yayımladı','Toz Pembe, 3 Temmuz 2026 tarihinde Hypers Music etiketiyle yayımlandı.',releases[9][3],'Apple Music’te 3 Temmuz 2026 tarihli tek şarkılık bir yayın olarak kayıtlı. Şarkı için resmî video bağlantısı da katalogda bulunuyor; dinleme ve video ayrıntıları şarkı sayfasından izlenebilir.'),
 ('pvg-live-remix-yayinda','2026-07-24','Manifest, Motive ve Pango’dan pVg canlı remiksi','pVg (Manifest Live Remix), 24 Temmuz 2026 tarihli ortak kayıt.',releases[10][3],'Apple Music bu single’da Manifest, Motive ve Pango’yu birlikte listeliyor. Yayının adı canlı remiks olduğu için özgün parçayla veya Manifest’e ait yeni bir stüdyo albümüyle karıştırılmıyor.')]
for slug,date,title,summary,url,body in news:entry('haberler',slug,title,date,summary,body+'\n\nKaynak kontrolü: 27 Eylül 2026.',url,seo_title=title+' | Manifest Haberleri',seo_description=summary)
entry('konserler','konser-2026-06-06','Manifest Ankara konseri: Manifestival 6 Haziran 2026','2026-06-06','Manifestival Ankara’nın ilk günü: Atatürk Orman Çiftliği, 6 Haziran 2026.','Biletix’in iki günlük Manifestival Ankara duyurusunda 6 ve 7 Haziran tarihleri yer alıyor. Bu kayıt ilk festival gününün arşividir. Grup için özel sahne gösterisi duyurulmuş olsa da program/saat ayrıntıları değişebileceğinden organizatörün resmî sayfası esas alınır.\n\nGeçmiş etkinliğin kesin gerçekleşme teyidi bu arşiv kaydının kapsamı değildir. Görsel, sahneden değil sanatçı arşivinden alınmıştır.\n\nKaynak kontrolü: 27 Eylül 2026.',bilet,city='Ankara',venue='Atatürk Orman Çiftliği',seo_title='Manifest Ankara Konseri 6 Haziran 2026 | Manifestival',seo_description='Manifestival Ankara’nın 6 Haziran 2026 günü Atatürk Orman Çiftliği duyurusu, kaynak ve festival bilgileri.')
entry('konserler','konser-2026-06-07','Manifest Ankara konseri: Manifestival 7 Haziran 2026','2026-06-07','Manifestival Ankara’nın ikinci günü: Atatürk Orman Çiftliği, 7 Haziran 2026.','Biletix’in iki günlük programına göre Manifestival Ankara 7 Haziran 2026 tarihinde de Atatürk Orman Çiftliği’nde duyuruldu. Bu kayıt festivalin ikinci gününe ayrılmıştır; kapı açılış saati, giriş kuralları ve sahne akışı için resmî bilet sayfası izlenmelidir.\n\nGeçmiş etkinliğin kesin gerçekleşme teyidi bu arşiv kaydının kapsamı değildir.\n\nKaynak kontrolü: 27 Eylül 2026.',bilet,city='Ankara',venue='Atatürk Orman Çiftliği',seo_title='Manifest Ankara Konseri 7 Haziran 2026 | Manifestival',seo_description='Manifestival Ankara’nın 7 Haziran 2026 günü, Atatürk Orman Çiftliği ve resmî bilet duyurusu.')
entry('konserler','konser-2026-10-16','Manifest Londra konseri: OVO Arena Wembley','2026-10-16','Manifest’in 16 Ekim 2026 Londra konseri, OVO Arena Wembley tarafından duyuruldu.','OVO Arena Wembley, Manifest’in 16 Ekim 2026 tarihindeki Londra gösterisini resmî etkinlik takviminde listeliyor. Konser duyurusunda XO eşlikçi olarak yer alıyor.\n\nSaat, bilet ve yaş koşulları değişebileceğinden etkinliğe gitmeden önce salonun güncel sayfasını kontrol edin. Kaynak kontrolü: 27 Eylül 2026.',venue,city='Londra',venue='OVO Arena Wembley',event_country='GB',event_timezone='Europe/London',seo_title='Manifest Londra Konseri 16 Ekim 2026 | OVO Arena Wembley',seo_description='Manifest’in 16 Ekim 2026 Londra konseri, OVO Arena Wembley, bilet ve salon duyurusu.')
# MusicBrainz/Shazam track order and durations, Apple release identity.
tracks=[('Intro',62),('Snap',150),('KTS',147),('Arıyo',133),('Manifest',150),('Zehir',185),('Hayır',129),('Zamansızdık',170),('Yaşanacaksa',166),('Durma',189),('Outro',86),('Rampapapam (Arem Ozguc & Arman Aydin Remix)',132),('Arıyo (Zeki Arkun Remix)',174),('Zehir (Motive Remix)',232),('Hayır (AYDEED Remix)',172),('Outro (Extended Version)',181)]
def slugify(name):
 import unicodedata,re
 s=name.replace('İ','i').casefold().replace('ı','i').replace('ğ','g').replace('ü','u').replace('ş','s').replace('ö','o').replace('ç','c').replace('&','-');return re.sub('-+','-',re.sub('[^a-z0-9]+','-',s)).strip('-')
def song(name,date,id,albumslug,albumtitle,source,position,duration,credits='',description=''):
 slug=slugify(name);v=dict(name=name,slug=slug,albumId=id,albumSlug=albumslug,albumTitle=albumtitle,date=date,cover=base if id in (a1,a2) else portrait,position=position,credits=credits or 'Manifest · Hypers Music',duration=duration,url=source,description=description or f'{name}, Manifest’in {albumtitle} yayınına ait kayıttır. Resmî dinleme bağlantısı ve sanatçı künyesi Apple Music üzerinden doğrulanmıştır.',videoId={'Amatör':'JzH6uWBtC3I','Daha İyi':'vso1LpaQRbo','Toz Pembe':'0pg0raFMNIU'}.get(name),videoSource=('https://www.youtube.com/watch?v='+{'Amatör':'JzH6uWBtC3I','Daha İyi':'vso1LpaQRbo','Toz Pembe':'0pg0raFMNIU'}[name] if name in {'Amatör','Daha İyi','Toz Pembe'} else ''))
 ops.append(dict(type='song',slug=slug,expectedRevision=revision('artist_songs',slug),status='published',values=v))
for i,(name,duration) in enumerate(tracks,1):
 id=a1 if i<=11 else a2;albumslug='manifestival' if i<=11 else 'manifestival-deluxe';albumtitle='manifestival' if i<=11 else 'manifestival (deluxe)';date='2025-06-13' if i<=11 else '2025-09-05';desc='Manifest’in 2025 tarihli yayını. '+('Çıtır Kızlar’ın Yaşanacaksa Yaşanacak eserine dayanan bir yorumdur.' if name=='Yaşanacaksa' else 'Deluxe sürümde yer alan ayrı düzenlemedir.' if i>11 else 'Albümün özgün parça sıralamasında yer alır.');song(name,date,id,albumslug,albumtitle,deluxe if i>11 else original,i,duration,'Manifest ve Pango' if name.startswith('Zehir') and i<=11 else 'Manifest, Arem Ozguc ve Arman Aydin' if name=='Manifest' else '',desc)
for slug,name,date,url in releases[2:]:
 base_name=name.replace(' (Ajda Pekkan ile)','');duration={'RÜYA':195,'Amatör':164,'Başrol Sensin (1. Yıl Özel)':193,'Manifest (Arem & Arman Remix)':153,'Zehir (Arem & Arman Remix)':174,'Daha İyi':199,'Hileli':202,'Toz Pembe':161,'pVg (Manifest Live Remix)':246}[base_name]
 song(base_name,date,release_ids[slug],slug,name,url,1,duration,'Manifest ve Ajda Pekkan' if slug=='hileli' else 'Manifest, Motive ve Pango' if slug.startswith('pvg') else '',f'{name}, {date} tarihli single kaydıdır. Yayın ve ortak sanatçı bilgisi Apple Music’te listelenir.')
# RÜYA and Amatör included in releases[2:] above. Album songs for debut single historical release share the album recording, no duplicates.
batch=dict(artist=artist,operations=ops)
Path('content/manifest/batch-20260927.json').write_text(json.dumps(batch,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'operations':len(ops),'entries':sum(x['type']=='entry' for x in ops),'songs':sum(x['type']=='song' for x in ops),'biography':sum(x['type']=='biography' for x in ops)}))
