'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
type C={id:string;target:string;username:string;body:string;created:number;updated:number;status:string};
export default function CommentsAdmin(){
 const [rows,setRows]=useState<C[]>([]),[status,setStatus]=useState('pending'),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const r=await fetch('/api/admin/comments?status='+status+'&offset='+offset,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setRows(d.comments);setMore(d.hasMore)}catch(e){setRows([]);setError(e instanceof Error?e.message:'Liste yüklenemedi.')}finally{setBusy(false)}}
 useEffect(()=>{void load()},[status,offset]);
 async function moderate(c:C,next:string){setBusy(true);try{const r=await fetch('/api/admin/comments',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:c.id,status:next,updated:c.updated})});const d=await r.json();if(!r.ok)throw Error(d.error);await load()}catch(e){setError(e instanceof Error?e.message:'İşlem başarısız.');setBusy(false)}}
 return <main className="admin-page"><Link href="/admin">← Yönetim / Giriş</Link><h1>Yorum onayı</h1><p>Misafir ve üye yorumları, onaylandıktan sonra sayfalarda görünür.</p><div className="comment-sort">{[['pending','Onay bekleyen'],['approved','Onaylanan'],['rejected','Reddedilen']].map(([value,label])=><button key={value} aria-pressed={status===value} disabled={busy} onClick={()=>{setStatus(value);setOffset(0)}}>{label}</button>)}</div>{error&&<p role="alert">{error}</p>}<div className="moderation-list">{rows.map(c=><article key={c.id}><strong>{c.username}</strong><time>{new Date(c.created).toLocaleString('tr-TR')}</time><small>{c.target}</small><p>{c.body}</p><div className="actions">{status!=='approved'&&<button className="primary" disabled={busy} onClick={()=>void moderate(c,'approved')}>Onayla</button>}{status!=='rejected'&&<button className="secondary" disabled={busy} onClick={()=>void moderate(c,'rejected')}>Reddet</button>}{status==='approved'&&<button disabled={busy} onClick={()=>void moderate(c,'pending')}>Onayı geri al</button>}</div></article>)}</div>{!busy&&!error&&!rows.length&&<p>Bu bölümde yorum yok.</p>}<div className="actions"><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-30))}>Önceki</button><button disabled={busy||!more} onClick={()=>setOffset(offset+30)}>Sonraki</button></div></main>;
}
