import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getSong,allSongs,songHref} from '@/lib/songs';
import {artists} from '@/lib/artists';
import Engagement from '@/components/engagement';
import ArtistChannel from '@/components/artist-channel';
import MobileNav from '@/components/mobile-nav';
import {siteOrigin,socialMetadata} from '@/lib/seo';
export const dynamic='force-dynamic';
type Props={params:Promise<{artist:string;slug:string}>};
const origin=siteOrigin;
export async function generateMetadata({params}:Props):Promise<Metadata>{const {artist,slug}=await params,s=await getSong(artist,slug);if(!s)return {title:'Şarkı bulunamadı',robots:{index:false}};const name=artists.find(a=>a.id===artist)?.name??artist,title=`${s.name} — ${name} Şarkısı`,description=`${name} sanatçısının ${s.albumTitle} albümündeki ${s.name} şarkısını ve ${s.videoId?'resmî YouTube videosunu':'albüm bilgilerini'} incele.`;return {title,description,alternates:{canonical:songHref(s)},...socialMetadata(title,description,songHref(s),s.cover),robots:{index:!!s.videoId,follow:true}}}
export default async function Page({params}:Props){const {artist,slug}=await params,s=await getSong(artist,slug);if(!s)notFound();const artistName=artists.find(a=>a.id===artist)?.name??artist,neighbors=(await allSongs(artist)).filter(x=>x.albumId===s.albumId),url=origin+songHref(s);const graph={ '@context':'https://schema.org','@type':'MusicRecording',name:s.name,byArtist:{'@type':'MusicGroup',name:artistName},inAlbum:{'@type':'MusicAlbum',name:s.albumTitle},url,image:s.cover||undefined,video:s.videoId?{'@type':'VideoObject',name:`${artistName} – ${s.name}`,embedUrl:`https://www.youtube-nocookie.com/embed/${s.videoId}`,url:`https://www.youtube.com/watch?v=${s.videoId}`} :undefined};return <><main className="song-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(graph).replace(/</g,'\\u003c')}}/><nav className="song-breadcrumb" aria-label="İçerik yolu"><Link href="/">Keşfet</Link> / <Link href={'/'+artist}>{artistName}</Link> / <Link href={'/'+artist+'/albumler/'+s.albumSlug}>{s.albumTitle}</Link> / {s.name}</nav><div className="song-hero">{s.cover&&<img src={s.cover} alt={`${artistName} – ${s.albumTitle} albüm kapağı`}/>}<div><p className="eyebrow">{artistName.toLocaleUpperCase('tr')} · ŞARKI</p><h1>{s.name}</h1><p>{s.albumTitle} albümünde {s.position}. sırada.</p><Link href={'/'+artist+'/albumler/'+s.albumSlug}>Albüm sayfasına git →</Link></div></div><section className="official-video"><h2>Resmî YouTube videosu</h2>{s.videoId?<><div className="video-frame"><iframe src={`https://www.youtube-nocookie.com/embed/${s.videoId}`} title={`${artistName} – ${s.name} ${s.videoKind==='klip'?'resmî klip':'resmî YouTube kaydı'}`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/></div><p>{s.videoKind==='klip'?'Resmî klip':'Sanatçının resmî YouTube kaydı'} · <a href={`https://www.youtube.com/watch?v=${s.videoId}`} target="_blank" rel="noopener noreferrer">YouTube’da aç ↗</a></p></>:<p>Bu şarkı için resmî YouTube videosu henüz doğrulanmadı. Yanlış bir videoyu resmî olarak göstermemek için oynatıcı eklemedik.</p>}</section><section className="song-neighbors"><h2>Albümdeki diğer şarkılar</h2><div>{neighbors.filter(x=>x.slug!==s.slug).map(x=><Link key={x.slug} href={songHref(x)}>{x.name} →</Link>)}</div></section><Engagement target={'song:'+artist+':'+s.slug}/><ArtistChannel artist={artist} name={artistName}/></main><MobileNav active="search"/></>}
