import {randomUUID} from 'node:crypto';
import {channelDb} from '@/lib/channel-db';
import {memberSession} from '@/lib/member-auth';
import {sameOrigin,adminSession} from '@/lib/admin-auth';
export const runtime='nodejs';export const dynamic='force-dynamic';
const json=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'no-store'}});
export async function GET(req:Request){const id=new URL(req.url).searchParams.get('post')??'',db=channelDb(),viewer=(await memberSession(req))?.id??null;const post=await db.prepare('SELECT id FROM fan_posts WHERE id=? AND deleted=0').bind(id).first();if(!post)return json({error:'Gönderi bulunamadı.'},404);const rows=await db.prepare(`SELECT c.id,c.body,c.created,m.username,CASE WHEN c.member_id=? THEN 1 ELSE 0 END AS mine FROM fan_post_comments c JOIN members m ON m.id=c.member_id WHERE c.post_id=? AND c.deleted=0 ORDER BY c.created DESC LIMIT 100`).bind(viewer??'',id).all();return json({comments:rows.results})}
export async function POST(req:Request){if(!sameOrigin(req))return json({error:'İstek doğrulanamadı.'},403);const member=await memberSession(req);if(!member)return json({error:'Beğenmek ve yorum yapmak için üye olmalısın.'},401);let d:Record<string,unknown>;try{d=await req.json()}catch{return json({error:'Geçersiz istek.'},400)}const id=typeof d.post==='string'?d.post:'',db=channelDb(),post=await db.prepare('SELECT id FROM fan_posts WHERE id=? AND deleted=0').bind(id).first();if(!post)return json({error:'Gönderi bulunamadı.'},404);if(d.action==='like'){const mine=await db.prepare('SELECT 1 FROM fan_post_likes WHERE post_id=? AND member_id=?').bind(id,member.id).first();if(mine)await db.prepare('DELETE FROM fan_post_likes WHERE post_id=? AND member_id=?').bind(id,member.id).run();else await db.prepare('INSERT INTO fan_post_likes(post_id,member_id,created) VALUES(?,?,?)').bind(id,member.id,Date.now()).run();return json({liked:!mine})}if(d.action==='comment'){const body=typeof d.body==='string'?d.body.normalize('NFC').trim():'';if(body.length<1||body.length>600)return json({error:'Yorum 1–600 karakter olmalı.'},400);const last=await db.prepare('SELECT created FROM fan_post_comments WHERE member_id=? ORDER BY created DESC LIMIT 1').bind(member.id).first<{created:number}>();const now=Date.now();if(last&&now-last.created<15000)return json({error:'Yeni yorum için 15 saniye bekle.'},429);await db.prepare('INSERT INTO fan_post_comments(id,post_id,member_id,body,created) VALUES(?,?,?,?,?)').bind(randomUUID(),id,member.id,body,now).run();return json({ok:true},201)}return json({error:'Geçersiz işlem.'},400)}
export async function DELETE(req:Request){if(!sameOrigin(req))return json({error:'İstek doğrulanamadı.'},403);const m=await memberSession(req),admin=adminSession(req);if(!m&&!admin)return json({error:'Üye olmalısın.'},401);let d:Record<string,unknown>;try{d=await req.json()}catch{return json({error:'Geçersiz istek.'},400)}const id=typeof d.id==='string'?d.id:'';if(!/^[a-f0-9-]{36}$/.test(id))return json({error:'Geçersiz yorum.'},400);const result=await channelDb().prepare(admin?'UPDATE fan_post_comments SET deleted=1 WHERE id=?':'UPDATE fan_post_comments SET deleted=1 WHERE id=? AND member_id=?').bind(...(admin?[id]:[id,m!.id])).run();return result.changes?json({ok:true}):json({error:'Yorum bulunamadı.'},404)}
